### ISSUE TITLE
VRPN Support for 3DConnexion SpacePilotPro USB HIDID c629

### ISSUE THREAD

**Issue by c4junkie** [vrpn/vrpn#10]
Hi,

therefore i'm unable to code by myself i'd like to request the support for the 3Dconnexion SpacePilotPro which is quite similar to the SpacePilot.
The only difference is the LED display which is not needed for navigation.
The USB HIDID is c629 and i hope that it is not a big issue to "fix".
Thanks in advance for you help.

Kind Regards,
                      c4junkie

**Comment by russell-taylor** [comment]
Closing this since the response has been a long time coming.
