### ISSUE TITLE
ntohd is undefined in vrpn_Phantom.C

### ISSUE THREAD

**Issue by sradigan** [vrpn/vrpn#105]
I am posting this as an issue, because I don't know the appropriate solution.

On line 1734 of file vrpn_Phantom.C
```
me->update_rate = ntohd(*((double *) p.buffer));
```

The issue is that ```ntohd()``` is not defined.  ```ntohd()``` is supplied by [winsock2](https://msdn.microsoft.com/en-us/library/windows/desktop/jj710200(v=vs.85).aspx) on windows, but I do not believe ```ntohd()``` exists on Linux (I'm not even sure if the phantom server would work on linux either).

After some investigating I found the ```VRPN_USE_WINSOCK2``` cmake variable, and thought that might clear things up, so with a fresh build directory and project generated I started the build, but it did not fix this.  Winsock2.h I believe is supposed to be included indirectly through the ```vrpn_Shared.h```.

I was told about the ```vrpn_ntohd()``` function by @ricortiz, which did make the library compile when used to replace ```ntohd()```.

The system is Windows 7 MSVS 2013

**Comment by russell-taylor** [comment]
Thanks for fixing this and sending a pull request!
