### ISSUE TITLE
Remove explicit setting of CMAKE_OSX_ARCHITECTURES

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#113]
See https://github.com/OSVR/OSVR-Core/issues/237

**Comment by russell-taylor** [comment]
Works for me.  I've been having trouble with this myself recently.  At one time, it was all the rage to build for both architectures so it made sense.  Go ahead and turn it off.

**Comment by rpavlik** [comment]
I think it's one of those things that's usually left up to the user to configure anyway, not the project.

**Comment by rpavlik** [comment]
I'm assuming some of the other stuff in the `if(APPLE)` section can also go - if cmake doesn't know how to mark a system include directory on Mac, there are bigger troubles.

**Comment by d235j** [comment]
Found another instance of this at vrpn/quat/CMakeLists.txt.

@rpavlik, can you merge https://github.com/vrpn/vrpn/pull/127?
