### ISSUE TITLE
VSE2013: unresolved external symbol _vrpn_gettimeofday

### ISSUE THREAD

**Issue by mastykin** [vrpn/vrpn#114]
Hello,
trying compile 29d138 in Visual Studio Express 2013 I get many of:
error LNK2001: unresolved external symbol _vrpn_gettimeofday

**Comment by russell-taylor** [comment]
That would be my fault.  I'm adding the ability to use std::chrono and didn't test the compile with it turned off.  Am fixing now.

**Comment by russell-taylor** [comment]
Sorry about that.  Turned a void * into a struct timezone * (which better matches what is expected), but didn't fix it in all code paths.  Should be in all of them now as of commit 5f28a90d0c62d5509563ef513e59b77cebf76aba
