### ISSUE TITLE
Keep fixing std::chrono changes and gettimeofday

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#118]
Some Visual Studio builds fail with std::chrono because struct timezone is not defined.  Better to change vrpn_gettimeofday() to take an OPTIONAL second pointer, and have that pointer be a void *, so that we don't expose everyone to an undefined structure.  Then we can move the time-zone definition into the C file and define it when it is needed (which it won't be for Chrono).

**Comment by rpavlik** [comment]
Thought I fixed that yesterday, it passed all the build combos on the OSVR ci, plus my local testing with MSYS2

**Comment by russell-taylor** [comment]
I just did a recursive clone and turned it on in osvr-core and had issues.  Could be because I was using Visual Studio 2013.  I think it makes sense to make the time zone optional, since at least I have never used it.  Way back when, it was a void *, so regressing that should still work for those who are using it.

**Comment by russell-taylor** [comment]
It compiles under VS2013, but not VS2015 for me.  Went ahead and pulled the definition back into the C file and made the pointer optional to make life easier for folks going forward if they are not using it.  Will issue a pull request.
