### ISSUE TITLE
 Could not open device when closing a server then opening a new one

### ISSUE THREAD

**Issue by agirault** [vrpn/vrpn#134]
Using VRPN commit 807ec7a on openSUSE Leap 42.1, I am working on an application which will run multiple medical simulations. Each simulation is independant and will be run in any order. Those simulations all needs specific devices for user interaction, therefore need a VRPN server. I do not wish to integrate the server handling in the main application and pass it to each simulation because :
1. I want to keep the simulation Logic in simulation classes and only deal with interfacing in the main application
2. We could potentially run the simulations separatly from the main application.

I first created a server and added a device :

```
this->connection = vrpn_create_server_connection();
this->vrpnAnalogDevice = std::make_shared<vrpn_3DConnexion_Navigator>(deviceName, this->connection);
```

I then call the `mainloop()` for those in a while loop followed by the references removal and deletion of the server connection : 

```
while(!this->terminateExecution)
{
    this->vrpnAnalogDevice->mainloop();
    this->connection->mainloop();
    std::this_thread::sleep_for(this->pollDelay);
}
std::cout<<"VRPNDeviceServer: removing connection references"<<std::endl;
this->connection->removeReference();
std::cout<<"VRPNDeviceServer: closing server"<<std::endl;
delete(this->connection);
```

When running my application and launching the simulation the first time, I see `VRPNDeviceClient: opening device0@localhost` once, then everything works and my client callbacks are called. Once I terminate the simulation, the following output shows : 

```
> VRPNDeviceServer: removing connection references
> VRPNDeviceServer: closing server
> vrpn_Connection::~vrpn_Connection: Connection was deleted while 1 references still remain.
> VRPNDeviceClient: closing device0@localhost
```

First surprise is that even though I called `removeReference()` there is still 1 reference remaining on the connection deletion.

After this, I start the simulation again. Here is my output : 

```
> vrpn_HidInterface::reconnect(): Could not open device 0004:0005:00
> VRPNDeviceClient: opening device0@localhost
> VRPNDeviceClient: opening device0@localhost
```

Launching a new simulation reruns all the code above. I do not understand why I get an error in `reconnect()` while I killed the previous connection, and why `openDevice()` is called twice.

**Comment by russell-taylor** [comment]
The reason for the remaining reference is that the analog device registers one.  You should delete it and then removeReference().  Note that after you do this, the object will have been deleted by the removeReference() call and you should not delete it again (or you will be deleting it twice).

Note that you can use the standard vrpn_server with an edited vrpn.cfg file to handle the server and you don't need to write your own.  If you are running multiple servers with different devices, you can specify different port numbers for each of them and have multiple running on the same machine.

While your description is very clear on many points (well done), I don't follow all of the above well enough to be certain of the answer to the restart question.  I will note that the device is still open (has not been deleted), so may be blocking the ability to re-open the same hardware device.  Presumably, if you kill the program and re-start than this is not an issue?  You could try deleting the driver object for the Navigator.

**Comment by rpavlik** [comment]
Also note that you can create the server connection with a static method of `vrpn_ConnectionPtr` which wraps the reference counting for you. Like Russ, I'm not sure how/why you're seeing this issue - if it's related to running the server internally or a certain way, or something specific to the device... If you were running the server in an external process or otherwise connecting to the device using the networking layer, the time between shutdown and startup of a process for being able to re-use that port can sometimes cause symptoms similar to the subject line, but not so much the rest of the description - I only mention it in case that's a detail that was left out and it provides some useful insight.

I'd also suggest trying the stock vrpn server with the config file - it should let you get around lifetime-related issues of device access, and if nothing else narrow down the source of the issue you're seeing.

**Comment by russell-taylor** [comment]
It has been awhile, so I'm assuming that one of the above fixes helped the issue.  If not, please reopen the issue.
