### ISSUE TITLE
VRPN tracking data from NDI Polaris Spectra seems highly variable

### ISSUE THREAD

**Issue by EvanKrueger** [vrpn/vrpn#157]
Hello!

I am currently attempting to use the Virtual Reality Peripheral Network (VRPN) to connect a Polaris Spectra optical tracking device to the Vizard VR software. The ultimate goal is to use the device for head and tool tracking.
The software that comes with the Polaris works correctly, tracking the rigid bodies packaged with the device with sub-milimeter accuracy. VRPN appears to support the Polaris tracking device and Vizard includes a VRPN plugin. However, when I use VRPN to interface with the Polaris, the data reported by VRPN seems to vary significantly, even when both the rigid body and the Polaris are connected to tripods.

I edited the vrpn.cfg file, adding the folowing, uncommented lines:

``` python
vrpn_Tracker_NDI_Polaris polaris COM2 1
../NdiToolDefinitions/8700449.rom
```

(I have confirmed that the Polaris device is connected to COM2. There is only one rigid body to be tracked, which is described by the 8700449.rom file. I also confirmed with the NDI sofware that comes with the Polaris that this is the correct file for the rigid body that I am attempting to track.)

I then run the vrpn_server.exe program, which reports the following:

``` posh
DEBUG Tracker_NDI_Polaris: num of rigidbodies 1
DEBUG Tracker_NDI_Polaris: filename >../NdiToolDefinitions/8700449.rom<
connected to NDI Polaris at default 9600 baud on device:COM2.
done
VRPN_Tracker_NDI_Polaris: Switching NDI to higher baud rate, and then reopening
com port at higher rate...done
```

In accordance with the wiki, I test that the tracking is working correctly by running vrpn_print_devices.exe in another cmd window:

``` posh
> vrpn_print_devices.exe polaris@localhost
```

``` posh
Opened polaris@localhost as: Tracker Button Analog Dial Text.
Press ^C to exit.

Tracker polaris@localhost, sensor 0:
        pos ( 0.07, 0.91, 0.00); quat (0.00, 0.01, 0.01, 0.00)
Tracker polaris@localhost, sensor 0:
        pos ( 0.07, 0.91, 0.01); quat (0.00, 0.01, 0.01, 0.00)
Tracker polaris@localhost, sensor 0:
        pos ( 0.08, 0.90, 0.00); quat (0.00, 0.01, 0.01, 0.00)
Tracker polaris@localhost, sensor 0:
        pos ( 0.11, 0.92, 0.99); quat (0.00, 0.01, 0.01, 0.00)
Tracker polaris@localhost, sensor 0:
        pos ( 0.05, 0.92, 0.01); quat (0.00, 0.01, 0.01, 0.00)
```

These jumps in position are very large, if I understand correctly that the scale here is in meters. 

Since the NDI software that came with the Polaris tracks the same rigid body very accurately, I am assuming that the jumps in position are not due to enviornmental factors (like IR light sources in the room, etc.). The rigid body is using the passive, retroreflective tracking dots. I am currently running VRPN on Windows 7.

Any help you can provide me would be greatly appreciated. 
Thank you!

**Comment by EvanKrueger** [comment]
Is it possible that this is a big/little endian issue?

**Comment by russell-taylor** [comment]
Doesn't look like endian issues.  I'll bet that the Polaris driver is non-compliant and is reporting millimeters or something other than meters.  Can you check and see if that is consistent with what you're seeing?

**Comment by EvanKrueger** [comment]
I do believe that this is a difference in scale. The Polaris reports positional measurements in the NDI software in millimeters, while (I am fairly sure) both VRPN and Vizard assume meters. 
I tested the equipment yesterday by placing both the Polaris and the known rigid body on tripods and measuring the position of the rigid body in two positions. The NDI software gives [x,y,z] displacement in millimeters with the magnitudes representing distance from the polaris tracker (which represents the origin). 

The Polaris reported:
> position1 = [19.6, 18.9, -1923.5] 
> position2 = [1.5,  15.4,  -1321.5]

>Which results in an absolute change of [18.1, 3.5, 602].

Just to be certain, I did confirmed those numbers with a tape measure, so I am confident that they represent the rigid body's position relative to the Polaris.

When I checked the position of the tracker in Vizard using tracker.getPosition(), it returned :

> position1 = [0.59, 0.59, 0.94]
> position2 = [0.41, 0.51, 0.46] 
> 
> Which results in an absolute change of [0.18, 0.08, 0.48]

The Vizard VRPN plug-in may also be having an effect on the numbers, but the positions of the tracked rigid body in both VRPN and Vizard were still jumping around a lot, so those positional numbers represent an average over a few seconds. That jumping around makes it a bit difficult to see a correlation between real-world movement and the virtual movement. 
(I've also attached a few seconds of video showing what it looks like when I link the view in Vizard to the tracked object.) [example_view.m4v.zip](https://github.com/vrpn/vrpn/files/342140/example_view.m4v.zip)


Is it possible that there is a parsing or sync issue? If there is any data I can provide or testing I can do to help diagnose the problem, please don't hesitate to ask. 
Thank you!


Just for reference, here's the code I use to connect Vizard to VRPN:
```
import viz
viz.go()

# add environment
viz.addChild('gallery.osgb')

# add tracker
vrpn = viz.add('vrpn7.dle')
tracker = vrpn.addTracker('polaris@localhost')
tracker.waitForConnection()
```

**Comment by russell-taylor** [comment]
What I'm trying to figure out is if the "jumping around" is caused by treating the reports as meters (which is correct in VRPN) when it may be incorrectly filled in in millimeters by the driver.  The best way to test this is probably to move the Polaris about a foot away from its original position and then see if the reported position changes by about 1000 times too much. If so, we'll modify the driver to report meters instead.  You could also test this by dividing the client-side report by 1000 and see if things behave as expected.

If it is the case that meters are being reported but the positions (and/or orientations, as it seemed from the video you sent) are noisier, then I think there is probably a sync/parsing issue where the reports are not getting handled correctly.

**Comment by EvanKrueger** [comment]
Hi Russell, 

I set up the Polaris and rigid body such that the rigid body was just beyond the minimum detection distance (~1 meter) and recorded the distance in both VRPN and Vizard during a 1 foot displacement. The results in both VRPN and Vizard seem to normalized [0:1], and, while the NDI software measured the displacement from the tracker in the z direction, the data (one trial is included in the attached Excel document) seems to show greatest displacement in the x axis. I'm not sure what to make of the magnitudes, as they seem to hit 1.0 and reset to 0. ([DisplacementTrial.xlsx](https://github.com/vrpn/vrpn/files/345340/DisplacementTrial.xlsx))

For reference, here's the Vizard code I used:
```python
import viz
import vizact

viz.go()

#Add environment
viz.addChild('gallery.osgb')

#Add the tracker
vrpn = viz.add('vrpn7.dle') 
tracker = vrpn.addTracker('polaris@localhost')
tracker.waitForConnection()

def print_info():
        x,y,z = tracker.getPosition()
	print '%.4f, %.4f, %.4f' % (x,y,z)
	
vizact.onupdate(0,print_info)
```

**Comment by russell-taylor** [comment]
Strange.  That looks like an endianness issue where the upper and lower order bytes of something are swapped, but...  the get_report() function is calling parse7CharsFloatFromNDIResponse() to get the values, and that function is reading an integer from an ASCII string so does not have an opportunity to expose endianness.  I wonder if the report length or format is not as expected by the parsing code.  The only way to debug that is to start printing out the reports in the get_report() function and making sure they match what is expected by the parsing code.  Maybe there is an extra field in there, or the length of the value strings has changed by one.

**Comment by EvanKrueger** [comment]
Hi Russell, 
(Apologies for my delayed reply – I was traveling for the last week.)

I looked at the vrpn_Tracker_NDI_Polaris.C code and compared it to the NDI API documentation. From what I can tell, the response string resulting from sending the Polaris the "TX " command looks to be correctly parsed. However, my handle on C/C++ is practically nonexistent, so if there is some non-obvious parsing problem, I'm not sure I'd catch it anyway. (If it helps in any way, I've attached both the section of the API documentation covering the TX command as well as the full API document, you likely have access to this information already.)

> [Polaris_API_Guide_commandTX.pdf](https://github.com/vrpn/vrpn/files/366780/Polaris_API_Guide_commandTX.pdf)
> [Polaris_API_Guide.pdf](https://github.com/vrpn/vrpn/files/366781/Polaris_API_Guide.pdf)

I do also have some sample code that came with the Spectra tracker, which includes parsing for the TX command. It appears that NDI's code converts parts of the response to hexadecimal first, but I have trouble following the process, so I'm not sure where it differs from VRPN's implementation.

Thank you for your help!

– Evan

```
/*****************************************************************
Name:				nGetTXTransforms

Inputs:
	bool bReturnOOV - whether or not to return values outside
					  of the characterized volume.

Return Value:
	int - 1 if successful, 0 otherwise.

Description:
	This routine gets the transformation information using the TX
	command.  Remember that if you want to track outside the
	characterized volume you need to set the flag.
*****************************************************************/
int CCommandHandling::nGetTXTransforms(bool bReturn0x0800Option)
{
	int
		nReplyMode = 0x0001,
		nNoHandles = 0,
		nHandle = 0,
		nRet = 0;
	unsigned int
		unHandleStatus = 0,
		unSystemStatus = 0;
	bool
		bDisabled = FALSE;
	char
		*pszTransformInfo = NULL;

	/* report in volume only or out of volume as well */
	nReplyMode = bReturn0x0800Option ? 0x0801 : 0x0001;

	memset(m_szCommand, 0, sizeof(m_szCommand));
	sprintf( m_szCommand, "TX %04X", nReplyMode );

	if(nSendMessage( m_szCommand, TRUE ))
	{
		if (!nGetResponse( ))
		{
			return 0;
		}/* if */

		if ( m_bDisplayErrorsWhileTracking )
		{
			if (!nCheckResponse(nVerifyResponse(m_szLastReply, TRUE )))
				return 0;
		}
		else
		{
			if (!nVerifyResponse( m_szLastReply, FALSE ))
				return 0;
		}/* else */

		/* TX Parsing Routines */
		pszTransformInfo = m_szLastReply;

		nNoHandles = uASCIIToHex( pszTransformInfo, 2 );
		pszTransformInfo+=2;

		for ( int i = 0; i < nNoHandles; i++ )
		{
			nHandle = uASCIIToHex( pszTransformInfo, 2 );
			pszTransformInfo+=2;

			bDisabled = FALSE;

			if ( strlen( pszTransformInfo ) < 18 )
				return 0;

			if( !strncmp( pszTransformInfo, "MISSING", 7 ) ||
				!strncmp( pszTransformInfo, "DISABLED", 8 ) ||
				!strncmp( pszTransformInfo, "UNOCCUPIED", 10 ))
			{
				if ( !strncmp( pszTransformInfo, "UNOCCUPIED", 10 ))
				{

					m_dtHandleInformation[nHandle].Xfrms.ulFlags = TRANSFORM_UNOCCUPIED;
					pszTransformInfo+=10;
					bDisabled = TRUE;
				} /* if */
				else if ( !strncmp( pszTransformInfo, "DISABLED", 8 ))
				{
					m_dtHandleInformation[nHandle].Xfrms.ulFlags = TRANSFORM_DISABLED;
					pszTransformInfo+=8;
					bDisabled = TRUE;
				} /* else if */
				else
				{
					m_dtHandleInformation[nHandle].Xfrms.ulFlags = TRANSFORM_MISSING;
					pszTransformInfo+=7;
				} /* else */
				m_dtHandleInformation[nHandle].Xfrms.rotation.q0 =
				m_dtHandleInformation[nHandle].Xfrms.rotation.qx =
				m_dtHandleInformation[nHandle].Xfrms.rotation.qy =
				m_dtHandleInformation[nHandle].Xfrms.rotation.qz =
				m_dtHandleInformation[nHandle].Xfrms.translation.x =
				m_dtHandleInformation[nHandle].Xfrms.translation.y =
				m_dtHandleInformation[nHandle].Xfrms.translation.z =
				m_dtHandleInformation[nHandle].Xfrms.fError = BAD_FLOAT;
			} /* if */
			else
			{
				m_dtHandleInformation[nHandle].Xfrms.ulFlags = TRANSFORM_VALID;

				if (!bExtractValue( pszTransformInfo, 6, 10000.,
									&m_dtHandleInformation[nHandle].Xfrms.rotation.q0 ) ||
					!bExtractValue( pszTransformInfo + 6, 6, 10000.,
									&m_dtHandleInformation[nHandle].Xfrms.rotation.qx ) ||
					!bExtractValue( pszTransformInfo + 12, 6, 10000.,
									&m_dtHandleInformation[nHandle].Xfrms.rotation.qy ) ||
					!bExtractValue( pszTransformInfo + 18, 6, 10000.,
									&m_dtHandleInformation[nHandle].Xfrms.rotation.qz ) ||
					!bExtractValue( pszTransformInfo + 24, 7, 100.,
									&m_dtHandleInformation[nHandle].Xfrms.translation.x ) ||
					!bExtractValue( pszTransformInfo + 31, 7, 100.,
									&m_dtHandleInformation[nHandle].Xfrms.translation.y ) ||
					!bExtractValue( pszTransformInfo + 38, 7, 100.,
									&m_dtHandleInformation[nHandle].Xfrms.translation.z ) ||
					!bExtractValue( pszTransformInfo + 45, 6, 10000.,
									&m_dtHandleInformation[nHandle].Xfrms.fError ) )
				{
					m_dtHandleInformation[nHandle].Xfrms.ulFlags = TRANSFORM_MISSING;
					return 0;
				} /* if */
				else
				{
					pszTransformInfo+=51;
				} /* else */
			} /* else */
			/*get handle status...*/
			if ( !bDisabled )
			{
				unHandleStatus = uASCIIToHex( pszTransformInfo, 8 );
				pszTransformInfo+=8;
				m_dtHandleInformation[nHandle].HandleInfo.bToolInPort = ( unHandleStatus & 0x01 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bGPIO1 = ( unHandleStatus & 0x02 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bGPIO2 = ( unHandleStatus & 0x04 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bGPIO3 = ( unHandleStatus & 0x08 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bInitialized = ( unHandleStatus & 0x10 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bEnabled = ( unHandleStatus & 0x20 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bOutOfVolume = ( unHandleStatus & 0x40 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bPartiallyOutOfVolume = ( unHandleStatus & 0x80 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bDisturbanceDet = ( unHandleStatus & 0x200 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bSignalTooSmall = ( unHandleStatus & 0x400 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bSignalTooBig = ( unHandleStatus & 0x800 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bProcessingException = ( unHandleStatus & 0x1000 ? 1 : 0 );
				m_dtHandleInformation[nHandle].HandleInfo.bHardwareFailure = ( unHandleStatus & 0x2000 ? 1 : 0 );

				/*get frame number...*/
				m_dtHandleInformation[nHandle].Xfrms.ulFrameNumber =
					uASCIIToHex( pszTransformInfo, 8 );
				pszTransformInfo+=8;
			} /* if */
			pszTransformInfo++; /*for the carriage return*/
		} /* for */

		unSystemStatus = uASCIIToHex( pszTransformInfo, 4 );
		m_dtSystemInformation.bCommunicationSyncError = ( unSystemStatus & 0x01 ? 1 : 0 );
		m_dtSystemInformation.bTooMuchInterference = ( unSystemStatus & 0x02 ? 1 : 0 );
		m_dtSystemInformation.bSystemCRCError = ( unSystemStatus & 0x04 ? 1 : 0 );
		m_dtSystemInformation.bRecoverableException = ( unSystemStatus & 0x08 ? 1 : 0 );
		m_dtSystemInformation.bHardwareFailure = ( unSystemStatus & 0x10 ? 1 : 0 );
		m_dtSystemInformation.bHardwareChange = ( unSystemStatus & 0x20 ? 1 : 0 );
		m_dtSystemInformation.bPortOccupied = ( unSystemStatus & 0x40 ? 1 : 0 );
		m_dtSystemInformation.bPortUnoccupied = ( unSystemStatus & 0x80 ? 1 : 0 );
		m_dtSystemInformation.bDiagnosticsPending = ( unSystemStatus & 0x100 ? 1 : 0 );
		m_dtSystemInformation.bTemperatureOutOfRange = ( unSystemStatus & 0x200 ? 1 : 0 );

	} /* if */

	/*
	 * reference tracking...apply at the end of all the parsing so that
	 * it is all the latest xfrms being applied
	 */
	ApplyXfrms();

	return 1;
} /* nGetTXTransforms */
```

```
/***************************************************************************
Name:               uASCIIToHex

Input Values:
	char
		szStr[]				:String of ASCII characters that make up a hex
							 integer value to be converted.
							 Note that the string may NOT be null-terminated.
	int
		nLen				:Length of input string.

Output Values:
	None.

Returned Value:
	unsigned int			:Integer equivalent of input array.

Description:
	This routine translates a character ASCII array which is
	hex to its equivalent integer value.

***************************************************************************/
unsigned int uASCIIToHex( char szStr[], int nLen )
{
	char
		chTemp;
	unsigned int
		uVal;
	int
		nCnt;

	uVal = 0;
	for ( nCnt = 0; nCnt < nLen; ++nCnt )
	{
		chTemp = szStr[nCnt];
		/*
		 * Convert hex ASCII digits to values to add to total value.
		 */
		if ( (chTemp >= '0') && (chTemp <= '9') )
		{
			chTemp -= '0';
		} /* if */
		else if ( (chTemp >= 'A') && (chTemp <= 'F') )
		{
			chTemp = 0x0000000a + (chTemp - 'A');
		} /* else if */
		else if ( (chTemp >= 'a') && (chTemp <= 'f') )
		{
			chTemp = 0x0000000a + (chTemp - 'a');
		} /* else if */
		else
		{
			/*
			 * We've hit a non-hex character.
			 */
			return( 0 );
		} /* else */

		/*
		 * Shift result into position of total value.
		 */
		uVal |= (chTemp << (4 * (nLen - 1 - nCnt)));
	} /* for */

	return( uVal );
} /* uASCIIToHex */
```

```
/*****************************************************************
Routine:    bExtractValue

Inputs:	pszVal - value to be extracted, uLen - length of value
		fDivisor - how to break up information, pfValue - data

Returns:

Description: This routine breaks up the transformation into
			 there individual components

*****************************************************************/
bool bExtractValue( char *pszVal, unsigned uLen,
					float fDivisor, float *pfValue )
{
    unsigned
        i;
    char
        szBuff[ 10 ];

    *pfValue = BAD_FLOAT;

    /*
     * Make sure that the first character is either a + or -.
     */
    if( *pszVal != '-' && *pszVal != '+' )
	{
      return false;
	} /* if */

    /*
     * Copy the + or - character to the buffer
     */
    szBuff[0] = *pszVal;

    /*
     * Copy the rest of the value.  Make sure that the remainder of
     * the value string contains only digits 0 - 9.
     */
    for( i = 1; i < uLen; i++ )
    {
        if( pszVal[i] < '0' || pszVal[i] > '9' )
		{
             return false;
		} /* if */

        szBuff[i] = pszVal[i];
    } /* for */

    /*
     * Null terminate the string.
     */
    szBuff[i] = '\0';

    *pfValue = float(atof( szBuff ) / fDivisor);
    
    return true;
} /* bExtractValue */
```

**Comment by russell-taylor** [comment]
I've never had much luck trying to debug parsing code without a device at hand to try it on.  I haven't used a Polaris device myself, but you might try sending a request to the mailing list to see if anyone has one working and can explain what you're seeing.

You may want to find someone with C++ experience to sit down with you and take a look at this onsite.  Sensics offers paid support for VRPN and in the past has done both on-site and cross-ship development work for clients, but you may be able to find someone local who is less expensive.
