### ISSUE TITLE
vrpn_Generic_server_object.C: 2 * bad widths ?

### ISSUE THREAD

**Issue by dcb314** [vrpn/vrpn#159]
1.

BUILD/vrpn-version_07.33/server_src/vrpn_Generic_server_object.C:2350]: (error) Width 511 given in format string (no. 2) is larger than destination buffer 'commStr[100]', use %99s to prevent overflowing it.

2.

BUILD/vrpn-version_07.33/server_src/vrpn_Generic_server_object.C:3109]: (error) Width 511 given in format string (no. 2) is larger than destination buffer 'mode[3]', use %2s to prevent overflowing it.

**Comment by russell-taylor** [comment]
Thanks!  Fixed in commit 5ceeb44ca07ccc4f736b22f6c2bc201549487784
