### ISSUE TITLE
union wait removed from recent glibc

### ISSUE THREAD

**Issue by ChristophHaag** [vrpn/vrpn#162]
Reference: https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commit;h=b49ab5f4503f36dcbf43f821f817da66b2931fe6

It's used here: https://github.com/vrpn/vrpn/blob/5ceeb44ca07ccc4f736b22f6c2bc201549487784/vrpn_Connection.C#L2548

Replacing it with `int wait` makes it compile but maybe there was a reason it was union wait instead and you want to look for alternatives.

**Comment by russell-taylor** [comment]
Fixed and pull requested in https://github.com/vrpn/vrpn/pull/163
Thanks for pointing this out!
