### ISSUE TITLE
Missing parameter for new vrpn_Tracker_DTrack

### ISSUE THREAD

**Issue by ka-ART** [vrpn/vrpn#177]
We found a small bug in server code when creating a new vrpn_Tracker_DTrack object: parameter act3DOFout was missing, so actTracing was taken instead by mistake.

Fix (rev:51c9d3e64fb4537d0548104c8cdba09d2dfcf68c):

@@ -2886,7 +2886,7 @@ int vrpn_Generic_Server_Object::setup_DTrack(char *&pch, char *line,
 
     _devices->add(new vrpn_Tracker_DTrack(s2, connection, dtrackPort,
                                           timeToReachJoy, nob, nof, pidbf,
-                                          actTracing));
+                                          act3DOFout, actTracing ) );
 
     return 0;
 #else

Thanks a lot,
Kurt

**Comment by russell-taylor** [comment]
Thanks for letting us know.  This has been fixed and pull requested in https://github.com/vrpn/vrpn/pull/178
