### ISSUE TITLE
VRPN for P5 Glove

### ISSUE THREAD

**Issue by danng007** [vrpn/vrpn#180]
Hi,
As http://www.vrgeeks.org/wiki/device-classification said, P5 Glove is able to use with VRPN (listed in input device). However, this device is not listed in vrpn.cfg and I'm unable to use it's data from VRPN.
Any solution for this? Thanks a lot.

Best,
Wantao

**Comment by russell-taylor** [comment]
The P5 driver is not built into the VRPN release.  Many vendors build VRPN into their native drivers; in those cases, there will not be an entry in vrpn.cfg and you'd connect to it using the device name published by the driver writer.

You might try running 'vrpn_print_messages localhost' on the machine where the glove is plugged in to find out what devices are emitting from there and what kind of messages they are sending.  If it cannot connect, then the driver is not exposing a VRPN interface on the standard port.
