### ISSUE TITLE
DTrack timestamp

### ISSUE THREAD

**Issue by sroettgermann** [vrpn/vrpn#184]
Is there a way of reading the timestamp from DTrack with VRPN?

**Comment by russell-taylor** [comment]
I see the following in the vrpn_Tracker_DTrack.C file:
    if(act_timestamp >= 0){  // use DTrack time stamp if available
    		tts = (long )act_timestamp;
    		ttu = (long )((act_timestamp - tts) * 1000000);
    		tts += timestamp.tv_sec - timestamp.tv_sec % 86400;  // add day part of vrpn time stamp
    
    		if(tts >= timestamp.tv_sec + 43200 - 1800){  // shift closer to vrpn time stamp
    			tts -= 86400; 
    		}else if(tts <= timestamp.tv_sec - 43200 - 1800){
    			tts += 86400;
    		}
    
    		timestamp.tv_sec = tts;
    		timestamp.tv_usec = ttu;
    }

so it looks like this is being done with a bit of an offset whenever the time code is available.

**Comment by sroettgermann** [comment]
I'm using the vrpn2unity package from DWilches https://github.com/DWilches/Vrpn2Unity and searching for a way to access the DTrack timestamp. I'm not that familiar with this, so maybe you can help me. That would be really nice.

**Comment by russell-taylor** [comment]
I don't know about getting the time stamp in Unity, but every message from VRPN has a timestamp associated with it.  When you receive the tracker state callback, it will have a timestamp field.  That field is the one filled in by the above code on the server and transported to the client.

**Comment by sroettgermann** [comment]
Okay, thank you @russell-taylor. I will contact DWilches regarding his integration. How to get the timestamp in Unity is not the issue. The problem is to get it from Vrpn2Unity I guess.
