### ISSUE TITLE
[Enhancement] Custom sysconfdir for installation

### ISSUE THREAD

**Issue by susnux** [vrpn/vrpn#185]
It would be nice if you can set a custom sysconfdir for the installation, because at the moment it installs the config into `/usr/etc` if you set `CMAKE_INSTALL_PREFIX` to `/usr` (as commonly done by distribution packagers).

E.g. something like this will do it:

    diff -Nur vrpn-07.33/server_src/CMakeLists.txt new/server_src/CMakeLists.txt
    --- vrpn-07.33/server_src/CMakeLists.txt        2015-01-17 17:16:12.000000000 +0100
    +++ new/server_src/CMakeLists.txt       2017-08-05 15:00:41.787122804 +0200
    @@ -138,6 +138,10 @@
            "${CMAKE_CURRENT_BINARY_DIR}/vrpn.cfg"
            @ONLY)
     
    +if(NOT SYSCONF_INSTALL_DIR)
    +       set(SYSCONF_INSTALL_DIR etc)
    +endif(NOT SYSCONF_INSTALL_DIR)
    +
     if(VRPN_INSTALL)
            if(WIN32)
                    install(FILES "${CMAKE_CURRENT_BINARY_DIR}/vrpn.cfg"
    @@ -145,7 +149,7 @@
                            COMPONENT mainserver)
            else()
                    install(FILES "${CMAKE_CURRENT_BINARY_DIR}/vrpn.cfg"
    -                       DESTINATION etc
    +                       DESTINATION ${SYSCONF_INSTALL_DIR}
                            COMPONENT mainserver)
            endif()

**Comment by russell-taylor** [comment]
This seems like a useful feature.  Go ahead and make a pull request.  Thanks!
