### ISSUE TITLE
Conversion from windows "filetime" to unix "timeval"

### ISSUE THREAD

**Issue by muellerand** [vrpn/vrpn#188]
This "possible" bug refers to file vrpn_Shared.C, line 588.
The time provided by windows is based on Jan 1, 1601, while the time under Unix starts on Jan 1, 1970.
To the best of my knowledge, this corresponds to a difference of 11644473600 seconds. Is there a reason why "vrpn" only subtracts 3054524608 seconds (approx. 96 years)?

**Comment by russell-taylor** [comment]
As I recall, we got that value empirically by comparing the times from a Windows machine and a Linux machine when we did the Windows port.  I haven't recently looked at how well this works, but it seems like running a server on a Windows machine and a client on a Linux machine and then printing the date and time from the time associated with a message on the Linux box would be the way to do this.

I'm surprised that it would be so far off.

**Comment by muellerand** [comment]
Many thanks for the prompt reply.
At the moment I have no linux machine available, but I installed vrpn on cygwin. I manually compared vrpn_gettimeofday on cygwin with the timestamp I get from "https://www.epochconverter.com". The two timestamps are more or less equal. Maybe 1 or 2 seconds off, but that's fine since my PC is synced with NTP. So that's the good news.
On windows, however, I get a timestamp (with vrpn_gettimeofday) which looks similar at first glance, but usually differs by more than 20000 seconds (???). Now, of course, these 20000 seconds are peanuts compared to the difference I estimated in my first comment. And it took me awhile to figure out what the problem was/is. But finally, I am pretty sure what is causing this strange behavior. The number of seconds since 01/01/1601 don't fit in an int32 (long). That's why you got this strange offset value, as vrpn does the conversion to long before the subtraction. So from my point of view, the solution is to change the order: First the subtraction (in microseconds or 100ns) and then the conversion to long. 
The offset value should then be around 11644473600 sec. Anyway, is there an argument for the empirical value and against the deterministic value?

**Comment by russell-taylor** [comment]
Deterministic is better than empirical.  I was just confused about how the empirical was so far from the deterministic and was wondering about a problem with the deterministic value.  Your research above seems to have turned up the reason for the discrepancy.  It would be great if you can make a pull request that fixes the truncation and sets the right value.

**Comment by muellerand** [comment]
Ok, I made a pull request.

**Comment by russell-taylor** [comment]
This happens again at line 963 for a different clock configuration setting, which is the default when std_chrono is turned off on VS2015.

**Comment by muellerand** [comment]
I will have a look at that (if you wish that), but I don't think that my previous changes affected the part where std_chrono is turned on. At the first appearance of the function get_time_using_GetLocalTime (line 568) Std_chrono and VRPN_UNSAFE_WINDOWS_CLOCK are turned off (isn't that the default configuration), while at the second appearance (line 891) Std_chrono is still off but on the other hand VRPN_UNSAFE_WINDOWS_CLOCK is on. As far as I can tell VRPN_USE_STD_CHRONO is only turned on between line 402-544. 

Just for clarification:
I guess the reason for this "unsafe windows clock mode" is that the quality of getlocaltime() is not very good. Right? And vrpn attempts to fix that by using this QueryPerformanceCounter, which starts at 0 every time one starts the machine. Because the time offset is still based on getlocaltime(), it only improves the quality of the measured time between two packets, but the absolute timestamp of an individual packet is still "crap".
Windows suggests to use GetSystemTimePreciseAsFileTime (in combination with FileTimeToLocalFileTime) for accurate absolute timestamps. But these functions require Windows 8 or higher. I guess that's not an option for you because you want to be compatible with as many platforms as possible.

**Comment by russell-taylor** [comment]
The std::chrono part is fine; it turns out that there are a couple of different version of non-chrono on Windows (with or without UNSAFE_WINDOWS_CLOCK and with or without V2).

The reason for the multiple versions is the multiple ways Windows has had over the years to do a high-resolution timer.  The reason it is called UNSAFE is because the performance clock varied based on the processor speed and was not set up to work with multiple processors back in the day.  This was code going back to Windows 95.

Line 963 is one of these alternative methods, not the std::chrono method.  It would be great if you could take a look at it as well.

Thanks for all your help!
