### ISSUE TITLE
Release with gcc6 support

### ISSUE THREAD

**Issue by paulbovbel** [vrpn/vrpn#193]
Hello VRPN maintainers,

I can't seem to build the last release (7.33) on ubuntu zesty/gcc 6. It looks like the build failure is resolved with this commit: https://github.com/vrpn/vrpn/commit/70d47fec7e3be85f5f05c8ac5be99dacbd8be257

Would you be so kind as to make a new release that includes that commit? Even an intermediary tag as a reference would be fantastic.

**Comment by russell-taylor** [comment]
@rpavlik It has been a couple of years since the last release.  I went ahead and made a draft release at https://github.com/vrpn/vrpn/releases/edit/untagged-e1ea9082cb8d586d66ec that uses the current master as its base.  I haven't done extensive testing on it, but I don't have access to my pool of devices that I had at UNC.  I can test with the ones I have around the house on various operating systems.

The biggest issue I know of that would determine what to release has to do with which version of HIDAPI we want to use; the newest versions fix some bugs but introduce others.

**Comment by rpavlik** [comment]
I've got a PowerMac G4 "Mirrored Drive Door" over here, so if I can figure out how to get the right version of xcode on it, I can at least test building and running on big endian.

**Comment by russell-taylor** [comment]
That would be most excellent!  I'll start testing devices.

**Comment by russell-taylor** [comment]
Devices work about as expected:
Windows
*	Logitech Extreme 3D raw
*	Logitech Extreme 3D OS native
*	X-keys shuttle/jog
*	Contour shuttle/jog
*	XBox 360 wired raw
*	XBox 360 wired OS
*	XBox 360 wireless raw
*	XBox360  wireless OS
?	Razer Hydra -- connects and streams data, but controller not lit or operating
*	nVidia Shield original
*	nVidia Shield new
*	Microsoft XBox One OS USB
*	Microsoft XBox One OS wireless
*	3DConnexion traveler

Linux
*	Logitech Extreme 3D raw
*	Logitech Extreme 3D OS native
*	X-keys shuttle/jog
*	Contour shuttle/jog
*	XBox 360 wired OS
x	XBox 360 wired raw -- Opened but OS captured inputs
*	XBox360  wireless OS
x	XBox 360 wireless raw -- Opened but OS captured inputs
?	Razer Hydra -- connects and streams data, but controller not lit or operating
*	nVidia Shield original -- Both raw interface and Joylin worked
*	nVidia Shield new -- Raw interface not working, OS has captured, Joylin worked
x	Microsoft XBox One raw
x	Microsoft XBox One OS
*	3DConnexion traveler

Mac
*	Logitech Extreme 3D raw
*	X-keys shuttle/jog
*	Contour shuttle/jog
x	XBox 360 wired raw (opens, but no response)
x	XBox 360 wireless raw (opens, but no response)
?	Razer Hydra (same as Windows)
*	nVidia Shield original
x	nVidia Shield new (Connects but no reports)
x	Microsoft XBox One raw
*	3DConnexion traveler (also controlled the mouse)

**Comment by russell-taylor** [comment]
Fixed a crash bug on Linux found in testing; it happened when connecting to a hostname that does not exist.

**Comment by russell-taylor** [comment]
@rpavlik I've got a draft release ready to go and am glad to release it whenever you are okay with me doing so.

**Comment by russell-taylor** [comment]
@rpavlik I'm going to go ahead and do this release.

**Comment by russell-taylor** [comment]
Sorry this took so long.  https://github.com/vrpn/vrpn/releases/tag/version_07.34 should be what you want.

**Comment by rpavlik** [comment]
Sorry for not getting around to testing it. Things got hectic.

**Comment by russell-taylor** [comment]
No worries.  Life can be hard.
