### ISSUE TITLE
Build vrpn client code in new VS solution

### ISSUE THREAD

**Issue by nfyfamr** [vrpn/vrpn#196]
Hello. I've got trouble with building VRPN client code.

Compiling the client_and_server project included in vrpn solution is well done. 
But when I tried to build same source code in new VS solution, Compiling is failed.
Error message is following:
`Error	LNK2019	unresolved external symbol _q_from_axis_angle referenced in function "public: __thiscall vrpn_Tracker_Spin::vrpn_Tracker_Spin(char const *,class vrpn_Connection *,int,double,double,double,double,double)" (??0vrpn_Tracker_Spin@@QAE@PBDPAVvrpn_Connection@@HNNNNN@Z)	vrpn_test	C:\Users\Lee\Desktop\vrpn\vrpn.lib(vrpn_Tracker.obj)`

Please, let me know how to solve it.

**Comment by russell-taylor** [comment]
You need to also link against the included quaternion library (quat.lib).
