### ISSUE TITLE
problems about the "Getting Started"

### ISSUE THREAD

**Issue by toriop** [vrpn/vrpn#198]
I follow the Getting Started pages(https://github.com/vrpn/vrpn/wiki/Getting-Started) to try to begin,
but when I move to the step: "build the quat, vrpn, vrpn_server, printvals and test_vrpn projects" 
when I built" vrpn_server", I always have many errors, and I don't know what should I do.....

![capture](https://user-images.githubusercontent.com/37078704/36984811-00598c06-2096-11e8-84e1-2014afb409ef.JPG)

**Comment by russell-taylor** [comment]
When I tried this in VS2015, I had a problem with the fact that the HIDAPI file seems to have changed its name from submodules/hidapi/windows/hid.c to hid.cpp.  This is handled in the CMake build by building HIDAPI as a submodule.  Let me see about fixing that and then I'll try again.

**Comment by russell-taylor** [comment]
Meanwhile, you can use the CMake build tool to construct a usable library and applications.

**Comment by russell-taylor** [comment]
Okay, the master branch now compiles for me under both Visual Studio 2015 and Cygwin.  Pull again and give it a try on your system.  If it is still failing, please specify which version of Visual Studio you are using.  Also, don't try to configure it for a DLL build.

**Comment by toriop** [comment]
Thank you so much! This time it can run (although there are some warnings),
 By the way, when I download the "vrpn-master" package from git , there is no file in the folders "hidapi" and "jsoncpp" and I have to copy files in these two folders manually(I am not sure if there is other missing file, because only the lack of these two folders cause errors)
In fact , I am a beginner of VRPN, I will continue studying. : )

**Comment by russell-taylor** [comment]
Glad to help.  If you 'git clone --recursive git@github.com:vrpn/vrpn.git' from the command line, it will pull those submodules along with it.  It is true that github does not do this when it creates the zip file.  You must have figured out already to do 'git submodule update --init' once it is here to get them.
