### ISSUE TITLE
A problem about build server

### ISSUE THREAD

**Issue by toriop** [vrpn/vrpn#204]
I am now using VRPN to realize the commnicate between Hololens and my computer.
In fact , after analyse the code, I find usually it is the server who send the message to a client.
so for example, if I want a hololens sends and receives messages; it should be both a server and a client?

**Comment by russell-taylor** [comment]
A server is written for the device that is to be communicated with (tracker, button device, analog, etc.).  That device may communicate both directions; a Phantom haptic display transmits pose data and button data and receives force-update data, for example.

The client side is connected to the application, and it talks with one or more servers to get access to devices.  This may be on the same computer (using loopback networking) or on a remote computer.

If you want to write a driver for the Hololens, you will derive it from one or more of the server device classes and then add it to the devices that can be launched from a server (see https://github.com/vrpn/vrpn/wiki/Writing-a-device-driver).  Other pages on the Wiki will probably be helpful as well.

**Comment by russell-taylor** [comment]
I'm going to go ahead and close this issue, but please don't hesitate to re-open it if this doesn't address your question.

**Comment by toriop** [comment]
How can a server receive data?
for example : if I have a device that can transmit and receive button data.
if I want to transmit button data, I just need to crear a vrpn_Button class and call vrpn_Button::report_changes();
but how to get button data?

**Comment by russell-taylor** [comment]
This is explained on the Wiki at https://github.com/vrpn/vrpn/wiki where there are links on the sidebar for how to make new server devices, which is the Writing-a-device-driver link from above.  By deriving from the button base class, a driver inherits the ability to send button data as you say.  You get button data by creating a remote device, as the vrpn_print_devices program does.

**Comment by russell-taylor** [comment]
https://github.com/vrpn/vrpn/wiki/Client-side-VRPN-Devices talks about the client-side devices and shows how to use them.  The ones that send data from the client to the server include the vrpn_Analog_Output, the vrpn_ForceDevice, and the vrpn_Poser.  You can also use the vrpn_Text_Sender class to send text data.

If you want to send another kind of data, it probably makes sense to looking into defining a new class of data that semantically matches what you need, as described in https://github.com/vrpn/vrpn/wiki/Creating-a-new-device-class.
