### ISSUE TITLE
the ip address problem

### ISSUE THREAD

**Issue by toriop** [vrpn/vrpn#207]
I have created a program about the commnicate between leapmotion and a unity program. it run prefectlly in my computer with "localhost". But when I use the program in my hololens in order to realize the commnicate between them, it seems never work.
I guess it maybe is the problem about setting ?
for example when I do this in my client side:
vrpn_Tracker_Remote	myTracker("Tracker0@ioglab.cs.unc.edu");
I should replace "ioglab.cs.unc.edu" by the ip address of my computer?

![image](https://user-images.githubusercontent.com/37078704/38799797-c6c1ff32-4165-11e8-8079-126c73b541e1.png)
in this situation, it should be "193.XXX.XXX.133"?

**Comment by russell-taylor** [comment]
Try using Tracker0@tcp://ioglab.cs.unc.edu to force it to bypass the UDP connections.  This can get around firewall issues on some systems.

If that doesn't work, try running the vrpn_server with a config that has the null device turned on on the hololens computer and then run vrpn_print_devices on the client and report the messages you get on the client and server.

**Comment by toriop** [comment]
I have try "Tracker0@tcp://193.XXX.XXX.133(my ip):3883" and "Tracker0@tcp://193.XXX.XXX.133(my ip)",but it throw the error:
![image](https://user-images.githubusercontent.com/37078704/38817268-4b213ebe-4198-11e8-80ad-9cd1370b9ef2.png)

if I don't add "tcp://", there is no error, but no data.

**Comment by toriop** [comment]
maybe it is the problem of my firewall which stop the UDP? But even if I close the firewall of widow, noting change....so maybe it is because the firewall of my school?

**Comment by russell-taylor** [comment]
I would have tried just Tracker0@tcp://193.XXX.XXX.133 but Tracker0@tcp://193.XXX.XXX.133:3883 should also work if the server is using the default port.  I definitely would not expect it to throw an exception.  What happens when you try running vrpn_print_devices Tracker0@tcp://YOUR_IP_ADDRESS on the machine that you are running Unity on?  This will debug the communications issues without involving Unity.

**Comment by toriop** [comment]
yes,you are right...if I run it in my computer, it will run prefectly. I think maybe it is the problem between unity and hololens.

**Comment by russell-taylor** [comment]
You can also test the other direction by running vrpn_server on the Hololens computer with a config file that has a null Tracker0 object that spits out the identity transform and see if Unity is able to connect to it.
