### ISSUE TITLE
vrpn_mouse not working in ubuntu 

### ISSUE THREAD

**Issue by IngEya** [vrpn/vrpn#208]
Hello,

I'm trying to test VRPN in ubutnu. I was able to test it in windows but in ubuntu when i launch the vrpn_server after removing the comment i get this error  
" vrpn_Mouse::vrpn_Mouse() not implemented on this architecture"

Could you please help?

Thanks

**Comment by russell-taylor** [comment]
"Help" in this case means "implement this class on a different architecture."  You probably want to take a look at the vrpn_DevInput device (see comments in the /server_src/vrpn.cfg file.
