### ISSUE TITLE
Polaris USB address already in use

### ISSUE THREAD

**Issue by IngEya** [vrpn/vrpn#209]
Hello
I am trying to use VRPN to connect with Polaris Spectra optical tracking device in a ubuntu virtual machine.

The software that comes with the Polaris works correctly, tracking the rigid bodies and it indicates that the Polaris device is connected to "/dev/ttyUSB0" port. I edited the vrpn.cfg file, adding the folowing, uncommented lines:

vrpn_Tracker_NDI_Polaris polaris /dev/ttyUSB0 1
/home/Rom_T-0501-5030.rom

There is only one rigid body to be tracked, which is described by the Rom_T-0501-5030.rom file.

**I then close every Polaris software so it disconnect from the corresponding port** and then when i run the vrpn_server.exe program it reports the following error ( However, i get the bip sound that indicates that it's connected to polaris):

![01](https://user-images.githubusercontent.com/35607659/38991693-73b7554e-43d6-11e8-897b-355f0519ec70.JPG)

**Comment by russell-taylor** [comment]
The parenthetical message about another application having the port open has always been the cause when I've seen this error happen.  Use netstat or something to find out what application has that port open.  The usual suspects are vrpn_server and built-in vendor drivers.

You can work around this by telling vrpn_server to use a different port and then connecting the client to that different port.  This also lets you run multiple VRPN servers on the same host.

**Comment by russell-taylor** [comment]
Sorry; I didn't look carefully at the first part of the error messages in your original post.  The problem with port 3883 being open in that case was that the first server was stopped with ^Z but had not been killed so still had the port open when the second server was run so the second server could not open it.

If this really was the 6th time this had been done, as the count of stopped jobs suggest, then it could be that the USB port had also been opened by a yet-previous VRPN server so could not be opened again.

You'll definitely want to kill (^C, not ^Z) all previous servers and not try to run a second or more on top of the first.  Once that has been done, hopefully the first one will be able to open the port.  If it is not, kill it (don't stop it) and then run the server as root.  It may be that only root has permission to open the port.

The thing that confuses me about the error message is where the message about finding 1 rigid body comes from -- at least one of the servers must have been able to open the port and read from it to report that message.

**Comment by IngEya** [comment]
I was wrong about the Polaris beep sound. The beep does not strictly means that the communication was done. But it's for alerting the users for major events (power on, communication timeout, communication reset) 
So in our case i'm guessing it's communication timeout. However i get this message just before the bug starts " connected to NDI Polaris at default 9600 baud on device:/dev/ttyUSB0.
done"

**Comment by IngEya** [comment]
I've just tested it as root and i still get the same error.

**Comment by russell-taylor** [comment]
My guess is that the same thing that has port 3883 open probably also has the USB device to the Polaris open, and that you're seeing interference with that app.  What happens if you point vrpn_print_devices at Tracker0@localhost on the machine where you normally run the server, running it without running your own server?  Does it connect?  If so, does it get tracker data?

**Comment by russell-taylor** [comment]
Were you able to resolve this?  If not, can you let me know what happened when you tried the things suggested in the previous message?
