### ISSUE TITLE
Regression betwen 7.33 and 7.34?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [vrpn/vrpn#223]
This is not a complete bug report and I don't know much about vrpn. But when I use vrpn 7.34 with our vicon system I get way more rotational outliers than when I use 7.33. Now I wonder if this is because 7.34 got better error reporting and the outliers are still there in 7.33 just not reported or if 7.34 caused some regression, where more rotational outliers are being produced. Any thoughts would be appreciated, since I am not sure with what version to best proceed.

**Comment by russell-taylor** [comment]
Thanks for bringing this up.  It turns out that the Vicon VRPN server is built into their system so presumably did not change when you upgraded your client-side applications to 7.34.  The two versions (7.33 and 7.34) should be compatible with one another.  Let me build both and make sure that the core servers interoperate properly with the client libraries.  There was some refactoring of the core communications objects in the system, but they were not expected to change the line protocol.  The changes to the vrpn_Tracker object did not affect the line protocol and were the addition of a new Spin tracker and memory-safety fixes.

**Comment by russell-taylor** [comment]
One thing to check is to make sure that the header files and libraries being used to compile the client application are consistent -- that it is not looking at the 7.33 headers but using 7.34 libraries or vice-versa.  The class members did change between the two.

**Comment by russell-taylor** [comment]
A version 7.33 server with a Null tracker can be connected to by a version 7.34 vrpn_print_devices program and seems to work normally.

Can you try running the vrpn_print_devices program that was compiled along with your VRPN and point it at the Vicon tracker to see if it is also having problems?

**Comment by russell-taylor** [comment]
Also, what operating system is your client running on?  I did my tests with Windows 10 Pro.

**Comment by russell-taylor** [comment]
@Kaju-Bubanja Any update on this?

**Comment by Kaju-Bubanja** [comment]
Thank you for the response. The client is running Ubuntu 16.04. The library is being compiled with the right headers. Using vrpn_print_devices I get this as output:
```
Tracker davis2@10.10.10.5, sensor 0:
        pos (-1.45,  1.17,  0.20); quat (-0.01,  0.23, -0.18,  0.96)
Tracker davis2@10.10.10.5, sensor 0:
        vel (-0.00,  0.00, -0.00); quatvel (-0.00, -0.00,  0.00,  1.00)
```
Does not look like there is an error there. I guess there is some randomness in the outlier reporting and there might be no real increase in outliers, just that I got randomly more in 7.34 than in 7.33. I guess this can be closed then.

**Comment by russell-taylor** [comment]
How are you finding out about the outliers?  Is this a VRPN warning message printed from a message sent from the server?  Is it an in-app message that you get by looking at deviations in the reports?  If it is a server-generated message, then I'm pretty sure you're right that it is just randomness.  If it is measured, it could still be randomness but you may want to look into it more.
