### ISSUE TITLE
Build dynamic .so instead of static .a?

### ISSUE THREAD

**Issue by jiapei100** [vrpn/vrpn#226]
Dynamic .so is preferred, but it seems it's NOT convenient to configure **--shared**???

**Comment by russell-taylor** [comment]
Dynamic libraries are often used when wrapping a language using Swig or other approaches to produce native code in Python or Java; VRPN has built-in flags to compile to those languages, creating the DLLs as needed to support that.

The client side of VRPN is intentionally lightweight, enabling a stripped executable that statically links the library and uses many device types to be as small as 265K in size.

The server side has a large number of configurable options regarding which devices are supported on a particular machine, making it advantageous to compile specifically for the running environment.

These factors make it often more convenient to use statically-linked VRPN in many projects.

There is no opposition to making it easier to link shared libraries; there is a CMAKE flag for that on Windows based on a patch that was submitted.  We'd be glad to accept a pull request that generalizes the flag for Linux.

**Comment by jiapei100** [comment]
The solution is comparatively simple, just
add **SHARED** for all **add_library** in **CMakeLists.txt** .
