### ISSUE TITLE
Code quality issues pointed out by LGTM.com

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#235]
To see the current list: https://lgtm.com/projects/g/vrpn/vrpn/alerts/

Most important:

- Range-check input values for allocation size to avoid overflow https://lgtm.com/rules/2157860315/ at  3 places in vrpn_Connection.C where there is `tbuf = new char[len];`
- thread safety: replace gmtime usage with gmtime_r https://lgtm.com/rules/2154840805/ in python/Device.cpp
- thread safety: get rid of ctime usage in vrpn_Flock.C (can probably use vrpn_gettimeofday instead of going with ctime_r)
- Overflow before conversion to wider type in vrpn_Imager.C (several places, see list)

minor: see list, takes longer to type them than fix them :)

**Comment by russell-taylor** [comment]
While it is true in theory that adding 1 to a string whose length is exactly the maximum length representable by size_t could overflow, there is no way to get that much memory so this is in practice not going to happen.  Interesting question whether it is better to slow down every call to these functions by adding a bounds check that will always succeed is worth the effort.  Gotta get that better score on the quality metrics, I guess...

**Comment by rpavlik** [comment]
lol, yeah, very true. This code analyst is a bit more false-positive-feeling than some of the other ones - I still stick with clang-tidy/clang static analysis as my main one

**Comment by russell-taylor** [comment]
How do we get it to run a new scan or find the summary page that only lists the remaining issues?

**Comment by russell-taylor** [comment]
Fixed the concerning issues, reported one as a false positive, and ignoring the rest. Leaving the issue open as a reminder to check the current alerts from time to time.

**Comment by russell-taylor** [comment]
LGTM has been shut down, so we won't be getting more quality updates from them.  This has been wrapped into Github code scanning.
