### ISSUE TITLE
Help Unity VRPN & Hololens howto 

### ISSUE THREAD

**Issue by tgrandpierre** [vrpn/vrpn#238]
Hello,

I need to build a unity  application on Hololens that read position from VRPN client connected to a VRPN server running on a PC.

I am able to make an app on unity that use VRPN (UVRPN) and connect to another PC (unity target= PC standalone)
I am able to develop an app on unity for the hololens (target : UWP Universal Windows Plateform)

But it's impossible for me to merge the 2 app (=adding uvrpn to my holo app) : I get the following message
"UVRPN/SharpConfig/Configuration.cs(157,41): error CS1644: Feature `expression bodied members' cannot be used because it is not part of the C# 4.0 language specification"

I guess the issue comes from the target that are different (UWP vs PC stand alone)
Does anyone succeed in running both simultaneously ??

(I use Unity 2018.4.3f1 & VS2017 & MixedRealityToolkit-Unity 2017.2.1.4)

**Comment by Okayuh** [comment]
Can WinUI 3 help this problem?

**Comment by russell-taylor** [comment]
Closing because this requires knowledge of integration with external systems and nobody has been able to provide it for awhile.  Please add comments to this issue if a solution was found.
