### ISSUE TITLE
vrpn_Local_HIDAPI.c cannot compile on linux

### ISSUE THREAD

**Issue by tomap44** [vrpn/vrpn#244]
The file vrpn_Local_HIDAPI.c contains the following:
`#elif defined(linux)
// On linux, we need to compile this code as C code rather than C++ code
// because otherwise the lack of casts from void* keeps it from compiling.
// Hopefully this will be fixed in a future version.  If so, we can then remove
// the special "compile this as C" line from the Makefile and the following
// check.
#ifdef __cplusplus
#error This code must be compiled as C code, rather than C++.  Use the '-x c' option to the compiler.
#endif`

It used to be compile with the '-x c' option, but this has been removed from the Makefile in the commit b208aea.

**Comment by russell-taylor** [comment]
Thank you for the clear error report.  It looks like that was trying to switch to a cpp file instead but must have missed the target.

**Comment by russell-taylor** [comment]
When I check out master recursively, so that it pulls the HIDAPI library, edit the Makefile to uncomment HW_OS to set it to pc_linux64, and then run 'make' on Linux, it is able to fully compile and link.  The file pc_linux64/server/vrpn_Local_HIDAPI.o is created along the way, indicating that the build system is still able to make it.

You can also add an executable to your path named hw_os that prints pc_linux64 if you don't want to edit the Makefile.

Can you give one of these a try and see if it works for you?

**Comment by russell-taylor** [comment]
The most supported VRPN build system is CMake.  For future work, you probably want to consider switching to it.  We do attempt to maintain the original build systems as well.

**Comment by russell-taylor** [comment]
I'm going to go ahead and close this issue.

**Comment by nm47** [comment]
I'm having the same issue as @tomap44, except using the build process you describe @russell-taylor. 
I'm downloading vrpn (git clone --recursive https://github.com/vrpn/vrpn.git), and then editing the makefile (uncommenting hw_os pc_linux64.
After running make I'm getting invalid conversion from 'void*' errors.

Any ideas what I'm doing wrong?

**Comment by russell-taylor** [comment]
@nm47 When I did this just now on Ubuntu 18.04 with g++ version 7.5.0, it compiles for me without warnings or errors:
```
git clone --recursive https://github.com/vrpn/vrpn.git
cd vrpn
vi Makefile
make
```

Note that you will have to also edit the Makefile in the server_src and client_src directories before building in them.

What system and compiler are you using?

**Comment by russell-taylor** [comment]
When I tried compiling just now I realized that we needed to add another object to the Makefile to link against the server library with the Makefile-based build, so I pushed a new commit.  This will fix a linker error.

**Comment by nm47** [comment]
Thank you very much! It works now (:
