### ISSUE TITLE
Consider switching to an updated hidapi library

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#251]
@rpavlik While trying to get things to run on a current Mac OS, I noticed that our hidapi version is no longer working.  The signal11/hidapi repository we branched from has not had updates in years, but there is a libusb/hidapi repository that has active development.  Neither of the two are a direct fork off the other, but the libusb repository has the patch you submitted for capitalization on the Windows header file.

How do you feel about us switching over to this repository?  You can check out the update-hidapi branch, which I've compiled and tested with some devices on Windows, MacOS, and Linux.  Given that the change has been pulled into the repository, we could then abandon the vrpn/hidapi repository (though we'd need to keep it around for people who are still building older versions).

**Comment by rpavlik** [comment]
I was happy to see that the libusb folks picked up where signal11 abandoned that repository. It would be great to get on mainline deps again. Is there any specific testing you want me to do? I think you named all the operating systems that I have, too :)

**Comment by russell-taylor** [comment]
Just wanted to check and see if you knew of a reason to go with something else.  Thanks!
