### ISSUE TITLE
vrpn_server build failed - OSVRHackerDevKit

### ISSUE THREAD

**Issue by Bukaj25** [vrpn/vrpn#252]
Hello

I have a problem to build vrpn_server, I already build quatlib and vrpn, I can build vrpn_print_device. I get LNK2019 error connected with OSVRHackerDevKit

`error LNK2019: unresolved external symbol "public: __thiscall vrpn_Tracker_OSVRHackerDevKit::vrpn_Tracker_OSVRHackerDevKit(char const *,class vrpn_Connection *)" (??0vrpn_Tracker_OSVRHackerDevKit@@QAE@PBDPAVvrpn_Connection@@@Z) referenced in function __catch$?setup_Mouse@vrpn_Generic_Server_Object@@IAEHAAPADPADPAU_iobuf@@@Z$0`

**Comment by russell-taylor** [comment]
How are you building (CMake, Makefile, Visual Studio project) and on what architecture (Windows 10, Ubuntu 18.04, MacOS)?

**Comment by Bukaj25** [comment]
> How are you building (CMake, Makefile, Visual Studio project) and on what architecture (Windows 10, Ubuntu 18.04, MacOS)?

I build it on Win10 with VS2019

**Comment by russell-taylor** [comment]
I'm sorry that you're having trouble.  Unfortunately, it looks like the OSVR developer kit has not been added to the list of devices in the Visual Studio files. 

To get working immediately, you can get CMake from cmake.org and open the VRPN source directory and select a build directory (that can be elsewhere on your computer).  It will configure things based on what libraries it can find on your system and can generate up-to-date Visual Studio 2019 files for you to build and install with.

The built-in Visual Studio project files have not been maintained for a number of years, so are not as reliable as using CMake to generate new build files.  We'll leave this issue open until they have been fixed.

**Comment by russell-taylor** [comment]
You actually got further than I did when I tried to compile the master branch out of the box using the supplied Visual Studio .sln file.  I ran into trouble with trying to include the HIDAPI files.  Did you perhaps configure those out?  If not, what commit of the code are you using?

Thanks,
Russ

**Comment by Bukaj25** [comment]
Thanks for your reply and answer ;) I see that I did not write the version of VRPN. I was tried build 7.33. 
When I'm trying build master branch I have an error while building vrpn lib and it is 
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'submodules/hidapi/windows/hid.cpp': No such file or directory	vrpn	MyPath\VRPN\vrpn\vrpn_Local_HIDAPI.C	12	`

i think it occurred because "submodules/hidapi" directory is empty

**Comment by russell-taylor** [comment]
Okay, I've merged a change to the master branch that uses an updated version of hidapi that is being maintained in another repository.  It should now compile for you using CMake.  Please verify and close the issue or else let me know what happened so we can get this buttoned up.  Thanks!

**Comment by russell-taylor** [comment]
The current master branch should have a working hidapi, so should fix this problem.  Please verify that it does and close the issue if so.  If not, let us know what remains to be fixed.  Thanks!

**Comment by russell-taylor** [comment]
I'm going to go ahead and close this issue.
