### ISSUE TITLE
vrpn_server build issue

### ISSUE THREAD

**Issue by htn3d** [vrpn/vrpn#255]
I am using VS 2019 and trying to build **vrpn_server** after I fixed HIDAPI issue and built **quatlib** and **vrpn** successfully but I am getting these errors:

> Error	LNK1120	1 unresolved externals	vrpn_server
> 
> Error	LNK2019	unresolved external symbol "public: __thiscall vrpn_Vality_vGlass::vrpn_Vality_vGlass(char const *,class vrpn_Connection *)" (??0vrpn_Vality_vGlass@@QAE@PBDPAVvrpn_Connection@@@Z) referenced in function __catch$?setup_Mouse@vrpn_Generic_Server_Object@@IAEHAAPADPADPAU_iobuf@@@Z$0	vrpn_server

I am a newbie to coding and not sure how to fix this problem. 
I trying to keep using VS2019 instead of CMake because CMake output didn't work with VR Geeks tutorials. my goal to build a custom standalone VRPN sever

Appreciate any advice

**Comment by russell-taylor** [comment]
I'm unable to build the master branch using the vrpn.dsw file because it was still looking for hid.cpp rather than hid.c in the vrpn_Local_HIDAPI.C file that is included by the vcproj files.  This did not get updated along with the CMakeLists.txt approach when we changed things.  I've updated that in the vsbuild branch.

Once I did that, I ran into other compiler errors having to do with wide-character support and UNICODE in the hid.c file in submodules/hidapi/windows.

If I undefine VRPN_USE_HID in vrpn_Configure.h, I am able to build and link the whole project in Release mode.

**Comment by russell-taylor** [comment]
No choice for vrpn/Properties/Advanced/Character Set is able to compile the entire project along with the HID code.  Some work with HID but not other files and others work with these files but not with HID.

**Comment by russell-taylor** [comment]
When I check out non-recursive and switch to commit c7c6a82679ccb3eae08001677cf9d3d68bb6d5fe and then do `git submodule update --init` to get the version before the switch to the more modern hidapi and change the hid.cpp to hid.c in vrpn_Local_HIDAPI.C, I get to the same Vality_vGlass linker error you found.

**Comment by russell-taylor** [comment]
I made a new **vsbuild** branch based off adding Vality and changing hid.cpp to hid.c.  Cloning without recursive, checking out that branch and then doing `git submodule update --init` let me open the .dsw file with VS2019 (which updated the solutions on open).  Building the Release configuration was able to complete after a few rebuilds to avoid file collisions.

**Comment by russell-taylor** [comment]
You're going to be much happier going forwards if you can use the CMake build.  Note that it can be installed to a system directory and then found there by a different project.  Also note that it does produce Visual Studio build files, just not the same ones that are in the directory.

**Comment by russell-taylor** [comment]
Anyway, go ahead and close this if the vsbuild branch gives you what you need.  Also, please issue a pull request if you find a way to get the master branch to build in the .dsw file with HID.

**Comment by htn3d** [comment]
> I'm unable to build the master branch using the vrpn.dsw file because it was still looking for hid.cpp rather than hid.c in the vrpn_Local_HIDAPI.C file that is included by the vcproj files. This did not get updated along with the CMakeLists.txt approach when we changed things. I've updated that in the vsbuild branch.
> 
> Once I did that, I ran into other compiler errors having to do with wide-character support and UNICODE in the hid.c file in submodules/hidapi/windows.
> 
> If I undefine VRPN_USE_HID in vrpn_Configure.h, I am able to build and link the whole project in Release mode.

Thank you so much for your response!
I tried to solve vrpn_local_HIDAPI.C issue by rename hid.c to hid.cpp and it worked, also changing LPVOID to LPWSTR at line 179 in hid.cpp passed me through vrpn build. but I stuck in vrpn_server

**Comment by htn3d** [comment]
I just cloned the new updated and it worked now I am able to build vrpn_server successfully. but after I change LPVOID to LPWSTR in hid.c because it kept giving the same error (not sure if that the right way to fix it but it worked). 

thank you so much again for your help

**Comment by russell-taylor** [comment]
You're welcome.
