### ISSUE TITLE
Intel Real Sense VRPN

### ISSUE THREAD

**Issue by DKZ-MAKER** [vrpn/vrpn#258]
Hello GitHub community people! Does any one know how to make intel real sense work with VRPN. Also, I have an old download with VRPN which works fine with HTC Vive trackers in Unreal Engine but I cant find EXE file in download link here.  Am I looking in the wrong place?

**Comment by russell-taylor** [comment]
For RealSense, Google turns this up: https://github.com/iebeid/realsense-tracking

Regarding the Vive, there is not a driver for it in the base library.  Google turns up the following: https://github.com/zhouhs88/vrpn-openvr

Regarding using VRPN trackers in Unreal, Google turns up this page https://docs.unrealengine.com/en-US/WorkingWithMedia/nDisplay/VRPN/index.html

**Comment by russell-taylor** [comment]
I'm going to go ahead and close this issue.

**Comment by DKZ-MAKER** [comment]
Yes. Thank you.
