### ISSUE TITLE
Python client always exits code

### ISSUE THREAD

**Issue by AndiHal** [vrpn/vrpn#262]
Hello,

I am trying to run the python interface in python (hand-coded version). I pulled this repository and made the setup with CMake. Then I built the "vrpn-python" project in Visual Studio. In the resulting Debug folder I now have the "vrpnd.pyd" file. 

I then try to use it in my python code with the following code: 

```
import sys 

sys.path.append('C:/Users/anh12by/vrpn/new_built/python/Debug')

import vrpn
```

However, as soon as the "import vrpn" statement is reached, the programm just exits. It says 
"Process finished with exit code -1073741819 (0xC0000005)"
So there is no crash but just an exit. Of course I googled the error code but it seems to be very situation specific how this is solved. I tryed to setup new Anaconda envrionments and run the code with different python versions, but the behavior remained the same. 

Is this maybe a know error? Or can someone guess what could be the problem?

Thanks a lot.

**Comment by russell-taylor** [comment]
Using CMake, I am able to set the VRPN/VRPN_BUILD_PYTHON_HANDCODED_3X entry.  When I build the resulting project in RelWithDebInfo, I get a python\RelWithDebInfo directory that has a vrpn.pyd in it.  When I run using the same Python version as was pointed to by PYTHON_LIBRARY in the CMake configuration in that directory, I can run the essai_3_2.py script after copying it into that directory.  When I run a server with a NULL tracker as Tracker0, I see reports printed.

I can also import vrpn in that directory and make a tracker remote directly.

I hope that this approach also works for you.

**Comment by AndiHal** [comment]
Thanks for your answer Mr. Taylor. 
I made the mistake that the built was set to Debug, not to RelWithDebInfo. 
Changing it, solved the issue :D
