### ISSUE TITLE
Improvements to C code for robustness

### ISSUE THREAD

**Issue by nhasabni** [vrpn/vrpn#263]
Hi,

I work at Intel, and we have developed a tool, named [ControlFlag](https://github.com/IntelLabs/control-flag), that detects anomalous programming language expressions that can possibly lead to bugs. We scanned the code repository for this project, and we found a couple of places where the code/expressions are confusing and seem to implement the logic in a rather convoluted manner. We think that the expressions could be rewritten to capture the logic accurately and precisely.

**Case 1)** Expression `(l_inbuf[2] | 1)` in the following code seems confusing because it would always evaluate to `true` as per C language. Was the intention to say `(l_inbuf[2] & 1)`? This is in line 108 below https://github.com/vrpn/vrpn/blob/c8465beb94de92b5083e9db50099eebd88ef6a41/vrpn_5DT16.C#L108-L113

**Case 2)** Similarly, expression `if (l_inbuf[3] | 1)` seems confusing. Was the intention to say `if (l_inbuf[3] & 1)`? This is in line 114 below https://github.com/vrpn/vrpn/blob/c8465beb94de92b5083e9db50099eebd88ef6a41/vrpn_5DT16.C#L114-L119

**Case 3)** Similarly, expression `if (l_inbuf[4] | 1)` seems confusing for the same reason. This is in line 194 below https://github.com/vrpn/vrpn/blob/c8465beb94de92b5083e9db50099eebd88ef6a41/vrpn_Analog_5dt.C#L194-L198

**Case 4)** For the same reason, expression `if (l_inbuf[5] | 16)` in line 199 look confusing. https://github.com/vrpn/vrpn/blob/c8465beb94de92b5083e9db50099eebd88ef6a41/vrpn_Analog_5dt.C#L199-L203

I would be happy to fix these issues, if someone can confirm them as bugs.

**Comment by russell-taylor** [comment]
Thank you for running these checks and for volunteering to fix the bugs! I can confirm them as bugs.

**Comment by nhasabni** [comment]
Hi @russell-taylor,

Thanks for confirming. I've created a pull request #264. Please take a look.

As a request - Would you (VRPN team) be okay if we reference it on ControlFlag's webpage? ControlFlag is also a fully open-sourced project. We would be happy to scan future versions of VPRN also!

**Comment by russell-taylor** [comment]
We're glad to have you reference this on the web page.  Thank you for your help.

Russ
