### ISSUE TITLE
Build in VS2019 from cmake generated sln

### ISSUE THREAD

**Issue by bedamco** [vrpn/vrpn#269]
Hi,
I am trying to build VRPN but I'm getting lots of errors, I did as instructed and used cmake to prepare a solution. The client seems to have compiled ok, but it's the server I need, and that has not compiled.

I'm on windows 10 using VS2019 and cmake 3.23.1

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0077	this declaration has no storage class or type specifier	add_vrpn_cookie	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\OAIdl.h	487	
Error (active)	E0065	expected a ';'	add_vrpn_cookie	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\OAIdl.h	487	
Error (active)	E0757	member "tagVARIANT::<unnamed>::<unnamed>::<unnamed>::_VARIANT_BOOL" is not a type name	add_vrpn_cookie	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\OAIdl.h	502	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2143	syntax error: missing ';' before '*' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2238	unexpected token(s) preceding ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXFFJoystick.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2143	syntax error: missing ';' before '*' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2238	unexpected token(s) preceding ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_DirectXRumblePad.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2143	syntax error: missing ';' before '*' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2238	unexpected token(s) preceding ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Warning	C4244	'initializing': conversion from 'double' to 'float', possible loss of data	Core VRPN Server Library	E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\vrpn_Tracker_zSight.C	93	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2143	syntax error: missing ';' before '*' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2238	unexpected token(s) preceding ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2144	syntax error: 'bool' should be preceded by ';' (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C2208	'bool': no members defined using this type (compiling source file E:\UE4_Projects\Code_projects\VRPN733\vrpn-master\server_src\vrpn_Generic_server_object.C)	Core VRPN Server Library	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_freespace	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	C2144	syntax error: 'bool' should be preceded by ';'	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2208	'bool': no members defined using this type	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	487	
Error	C2143	syntax error: missing ';' before '*'	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2238	unexpected token(s) preceding ';'	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\oaidl.h	502	
Error	C2144	syntax error: 'bool' should be preceded by ';'	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	C2208	'bool': no members defined using this type	directXFF	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\propidlbase.h	319	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_peerMutex	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	client_and_server	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_logging	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file 'Debug\vrpnserverd.lib'	time_test	E:\UE4_Projects\Code_projects\vrpn733_mid\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	testSharedObjectServer	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	testimager_server	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_rumble	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_radamec_spi	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_loopback	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_vrpn	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_analogfly	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	forward	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	test_auxiliary_logger	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	textServer	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	last_of_sequence	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	sample_server	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	nidaqClient	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1	
Error	LNK1104	cannot open file '..\Debug\vrpnserverd.lib'	vrpn_server	E:\UE4_Projects\Code_projects\vrpn733_mid\server_src\LINK	1

**Comment by russell-taylor** [comment]
When I compile from the current master branch 777a6872e25ba42e9ac7e4b083302849861b6259 using CMake 3.22.3 and a just-updated Visual Studio 2019 on Windows 10 using no changes to the default settings it builds successfully for me in the Debug x64 configuration, including the main server library and the vrpn_server application.  Also RelWithDebInfo and Release.

Please include the commit has for the source you are using (`git log` will show you this for the topmost entry).

From the error messages, it appears that there is a problem with either the configuration header or with an OS include.

**Comment by russell-taylor** [comment]
Please also tell of any changes you made to the default configuration in CMake before generating the build files.

**Comment by russell-taylor** [comment]
Closing as non-reproducible.  Please reopen and add info if you're still having this problem.
