### ISSUE TITLE
Clock skew on Windows

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#27]
Putting a test for the latency between message receipt (msg_time) and callback receipt (gettimeofday) in the tracker handler in the rendering program reports varying latencies around 12ms for a server running at 60fps.
  Slightly less for a server running at 250.
Putting a test in vrpn_print_devices shows a more consistent latency of around 23ms for a server running at 250.
  Removing the sleep in vrpn_print_devices makes it 30ms.
  Putting the sleep back in makes it 37ms.
  Running again makes it 39ms.
  Running again makes it 43ms.
  Rerunning the server and then the print devices makes it 1-2ms.
  Running it again makes it 10ms.
  Running a second copy later with the first still running has 15ms on the later and still 10ms on the first.  And running a third simultaneous copy has 23 with the others still at 15 and 10.
  This latency also goes up with the NULL tracker.Â  It seems to be also a factor of time between connections.  And one time I ran a server it didn't happen.

Check the high-resolution Windows timer code, it may get the rate wrong.

**Comment by rpavlik** [comment]
May consider looking at what Boost.Chrono does for its timing on Windows.

**Comment by rpavlik** [comment]
https://github.com/boostorg/chrono/blob/master/include/boost/chrono/detail/inlined/win/chrono.hpp, and https://github.com/boostorg/winapi/blob/master/include/boost/detail/winapi/time.hpp

**Comment by rpavlik** [comment]
plus https://github.com/boostorg/winapi/blob/master/include/boost/detail/winapi/timers.hpp

**Comment by rpavlik** [comment]
Also, food for thought:
http://stackoverflow.com/questions/25892392/using-different-api-for-different-windows-versions-efficiently

Win8+ has a fancy-pants high precision timestamp available, and you can use it with getprocaddress to avoid hard-depending on it.

**Comment by rpavlik** [comment]
Oh, but apparently it's slow: https://cygwin.com/ml/cygwin/2013-06/msg00157.html

**Comment by russell-taylor** [comment]
Implemented a version of the clock that uses std::chrono.  On Visual Studio 2015 (not 2013), this produces a high-resolution clock.  Will test to see if this avoids different clocks on different threads.

**Comment by russell-taylor** [comment]
It does seem to avoid skew.  Closing the issue.
