### ISSUE TITLE
Consider making VRPN server verbose by default

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#277]
The VR Geeks tutorial says that the program will list the server it is opening, which currently only happens with the '-v' option.

Consider adding a quiet option and making verbose the default so it remains consistent with tutorials but also can be made quiet if desired.

**Comment by rpavlik** [comment]
I would be in favor of this too. When I remember, I always use verbose mode.

**Comment by russell-taylor** [comment]
This has been added in https://github.com/vrpn/vrpn/pull/279
