### ISSUE TITLE
Glob for python version does not match python >= 3.10 correctly

### ISSUE THREAD

**Issue by StefanBruens** [vrpn/vrpn#280]
https://github.com/vrpn/vrpn/blob/e2ebd90aa3bce620ef1f2936534efcaebb14178e/python/CMakeLists.txt#L6-L8

With Python 3.10/3.11 `PYTHONVERSIONDIR` is expanded to `python3.1`.

**Comment by russell-taylor** [comment]
Thanks for pointing this out!  If you fix it, please go ahead and issue a pull request. Otherwise, something for me to look at over the holidays. :-)

**Comment by russell-taylor** [comment]
Fixed in 1b4676b3cf8bbaff2f75c8e41b005401b189b2e2
