### ISSUE TITLE
Packager Request: c_interface_example should be prefixed

### ISSUE THREAD

**Issue by seichter** [vrpn/vrpn#284]
I have created a new AUR package for VRPN (https://aur.archlinux.org/packages/vrpn) which takes the vanilla source package and builds it for the appropriate targets. One things caught my eye is that `c_interface_example` is being build with the clients and installed. It has no prefix and lands in `/usr/`, which is awkward. It would be great if you could prefix it, so it ends up with something like  `vrpn_c_interface_example`

**Comment by rpavlik** [comment]
As an example does it actually need to be installed at all? Unlike e.g. vrpn_print_devices and vrpn_server there's not a ton of use for it on its own, is there?

**Comment by russell-taylor** [comment]
@seichter Thank you for making a package for VRPN.  Glad to help clean things up.

@rpavlik Good call. I've move the program from Tests to Clients in the Visual Studio list and removed the installation line for it in 661a2d54f64f39ffa636cecb321f13f528d3c37e.
