### ISSUE TITLE
Import vrpn causes segmentation fault on Mac pro M1

### ISSUE THREAD

**Issue by avv-va** [vrpn/vrpn#287]
Hi, 

I am trying to install python_vrpn on my m1 Pro with Miniconda. Here are the steps I followed:
- I downloaded the latest [release](https://github.com/vrpn/vrpn/releases/tag/version_07.35)
- I made these changes in my `vrpn/python_vrpn/Makefile.python`:
       - PYTHON_VER := 3.10
       - PYTHON_INCLUDE_DIR := /Users/ava/miniconda3/bin/python$(PYTHON_VER)
       - PYTHON_PACKAGES_DIR := /Users/ava/miniconda3/lib/python3.10/site-packages
- mkdir vrpn/build && cd build
- cmake ..
- make vrpn-python
- sudo make install vrpn-python

It successfully performed all these steps. However when I tried executing `python3.10 -c "import vrpn"` it couldn't find it. so I manually copied the `vrpn.so` from the vrpn/build directory to `$(LIB_DIR)/python$(PYTHON_VER)/site-packages`.
After that, when I executed `python3.10 -c "import vrpn"` it returned a segmentation fault error. So I used the faulthandler library to trace the error and here is the result:

```
Fatal Python error: Segmentation fault

Current thread 0x00000001049a8580 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<stdin>", line 1 in <module>
zsh: segmentation fault  python3.10

```

I would appreciate your help! Thanks

**Comment by russell-taylor** [comment]
Try the current master branch. There was a fix in January to make Python versions > 3.9 work correctly.

**Comment by avv-va** [comment]
Still not working. Also, I realised when I run cmake, it outputs this warning:
```
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) 
-- Found PythonLibs: /opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib (found version "3.11.3") 
CMake Warning (dev) in CMakeLists.txt:
  A logical block opening on the line

    /Users/ava/vrpn/CMakeLists.txt:348 (if)

  closes on the line

    /Users/ava/vrpn/CMakeLists.txt:353 (endif)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Java: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java (found version "17.0.6") found components: Development 
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT) 
-- Checking for module 'mpi-c'
--   No package 'mpi-c' found
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Checking for module 'mpi-cxx'
--   No package 'mpi-cxx' found
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 
-- Could NOT find Modbus (missing: MODBUS_LIBRARY MODBUS_INCLUDE_DIR) 
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.26
-- Found Libusb1: /opt/homebrew/lib/libusb-1.0.dylib  
-- Could NOT find HIDAPI (missing: HIDAPI_LIBRARY HIDAPI_INCLUDE_DIR) 
-- Could NOT find OpenHaptics (missing: HDAPI_LIBRARY HDAPI_INCLUDE_DIR HDAPI_HDU_INCLUDE_DIR HDAPI_HDU_LIBRARY HLAPI_INCLUDE_DIR HLAPI_LIBRARY HLAPI_HLU_INCLUDE_DIR HLAPI_HLU_LIBRARY HDAPI_PHANToMIO_LIBRARY HDAPI_HDU_SOURCE_DIR HLAPI_HLU_SOURCE_DIR) 
-- Could NOT find GHOST (missing: GHOST_LIBRARY GHOST_INCLUDE_DIR) 
-- Could NOT find I2CDEV (missing: I2CDEV_INCLUDE_DIR) 
-- Could NOT find WiiUse (missing: WIIUSE_LIBRARY WIIUSE_INCLUDE_DIR) 
-- Could NOT find JsonCpp (missing: JsonCpp_INCLUDE_DIR JsonCpp_LIBRARY) 
-- Could NOT find LibNifalcon (missing: LIBNIFALCON_LIBRARY LIBNIFALCON_INCLUDE_DIR) 
-- Could NOT find GPM (missing: GPM_LIBRARY GPM_INCLUDE_DIR) 
-- Could NOT find InterSense (missing: INTERSENSE_LIBRARY INTERSENSE_INCLUDE_DIR) 
-- Could NOT find NIDAQmx (missing: NIDAQMX_LIBRARY NIDAQMX_INCLUDE_DIR) 
-- Could NOT find ViewPoint (missing: VIEWPOINT_LIBRARY VIEWPOINT_INCLUDE_DIR) 
-- Found Perl: /usr/bin/perl (found version "5.30.3") 
-- Checking for perl module Parse::RecDescent
-- Checking for perl module Parse::RecDescent - found at /System/Library/Perl/Extras/5.30/Parse/RecDescent.pm
-- Found PerlModules: TRUE  
-- Could NOT find LibFreespace (missing: LIBFREESPACE_LIBRARY LIBFREESPACE_INCLUDE_DIR) 
-- Found quatlib: quat  
-- Could NOT find ColibriApi (missing: COLIBRIAPI_LIBRARY COLIBRIAPI_INCLUDE_DIR CMAKE_HAVE_THREADS_LIBRARY) 

```

**Comment by russell-taylor** [comment]
Just took a closer look at what you were doing. Unfortunately, there are a couple of different Python approaches built into VRPN and the approach taken above mixes the two of them. See the README.python file for more information.

The version in python_vrpn was made for building against a VRPN that was compiled in-place using the Makefile rather than one that was built using CMake. The author's email is in the Makefile.python, perhaps he can help get that working.

The version in python is from another author and it has been incorporated into the CMakeLists.txt build. To get it working requires setting CMake variables rather than editing Makefile.python in the subdirectory. You'll want to set VRPN_BUILD_PYTHON_HANDCODED_3X. This was not designed to work with conda environments, so it may be tricky to get it to build that way. I haven't tried that.

Give a try with the CMakeLists.txt approach and see if that gets you closer.

**Comment by russell-taylor** [comment]
I am able to build using this approach on Linux. I don't know if CMake is able to find Python libraries on the mac in a conda environment.

**Comment by russell-taylor** [comment]
I was not able to get the current version working on my M1 mac, so I made a branch named *updated_python* that uses a newer approach that did work for me. Give it a try and see if it works. I'm planning to test on other architectures and then merge into master assuming it works on all of them.

**Comment by avv-va** [comment]
I just tried the updated_python branch, and it worked. Thank you very much!
