### ISSUE TITLE
Compilation error MinGW: redefinition of 'struct timezone'

### ISSUE THREAD

**Issue by chris-hld** [vrpn/vrpn#289]
Redefining 'struct timezone' in `vrpn/vrpn_Shared.C:28:8`
also defined in 
`time.h:295:8`.

At least `time.h` seems to guard the definition under windows with `_TIMESPEC_DEFINED`, so this guard should be added to VRPN in order to avoid compilation errors.

**Comment by russell-taylor** [comment]
Closed with your pull request -- thank you!
