### ISSUE TITLE
Windows serial port mgmt

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#29]
So it looks, per this page, that the feature allowing `\\.\COM13` or similar is a Windows NT feature. This is the best reference I've found on it.

http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#win32_device_namespaces

Not sure if it's worthwhile to detect NT and automatically try this if we fail to open a serial port.

**Comment by russell-taylor** [comment]
I modified the error message to tell about this naming condition in the case where the port cannot be opened on Windows.
