### ISSUE TITLE
Network connections fail on Windows 8.1

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#32]
On my new ASUS Laptop, the test_logging code fails because the code cannot establish a connection to itself over localhost.  No connection requests received, so it looks like the UDP packets are getting blocked.  Told Windows to allow access to the program when the security dialog came up.
Visual Studio 2013 Express.
Latest source code also fails.  Version 7.31 also fails.
Works on a mac, as does the latest source code.
Works on a Windows 7 64-bit machine. Works on other Windows 8 machines.

**Comment by rpavlik** [comment]
Is this the standard windows firewall?

**Comment by russell-taylor** [comment]
I tried adding an outgoing UDP rule to the firewall for the app; no luck.  I tried turning off the firewall completely; no luck.  If I make a TCP-only connection, that works fine.  I checked the message in the packet, and it is 127.0.0.1 with a reasonable number for a random port.

**Comment by russell-taylor** [comment]
Running a server on the Windows machine and connecting via the standard UDP-initiated message from a Linux machine on the local network works fine.  I can connect a remote vrpn_print_devices to the local vrpn_server running on Windows and things are good.

**Comment by russell-taylor** [comment]
When I try a standard connection from vrpn_print_devices running on the Windows host to the same Linux box running vrpn_server, the Linux box does not see any incoming UDP requests.  Putting print statements in the vrpn_Connection reveals that it is connecting the UDP port to 192.168.0.250, port 3883 with a NULL NIC name.  That's the right machine name and port.

**Comment by russell-taylor** [comment]
Also fails for vrpn_print_devices compiled with Cygwin on the same host.  Pings to that machine work.  TCP VRPN connections work.  Turning off the firewall doesn't help.

**Comment by russell-taylor** [comment]
Everything looks right in the world.  vrpn_connect_udp_port get a reasonable port number on the correct interface.  The socket type is UDP.  The port number and machine to connect to match.  No errors on the system calls.

**Comment by russell-taylor** [comment]
Okay, wow.  If I put a sleep in after the send() but before closing the socket, we're golden.  It looks like the socket is being closed before the packet goes out.  Will find a real fix soon.  Huzzah!

**Comment by russell-taylor** [comment]
Fixed in commit df35c01f5f6e80a9e7b8c169e9241e445be91af6 in the UNC VRPN master.
