### ISSUE TITLE
Provide snprintf

### ISSUE THREAD

**Issue by godbyk** [vrpn/vrpn#34]
Visual Studio 2008 doesn't provide `snprintf` so we can't currently use it in the VRPN code base.

Since `sprintf` is a frequent source of buffer overruns, we should provide a safe implementation of `snprintf` that can be used throughout the code base.

**Comment by russell-taylor** [comment]
Lets go with std::string.  You all have convinced me that it is time to embrace the standard library in VRPN.  In fact, I may switch out the parameter-passing code in the YEI to use this, rather than augmenting it with a second way.
