### ISSUE TITLE
Initialize d_sender_id to some sentinel "invalid" value in BaseClassUnique

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#41]
Would make it easier and more reliable to detect ordering issues (that is, calling things that use it before calling `vrpn_BaseClass::init`) - right now it's a read of an uninitialized location which is undefined behavior - so it might give you garbage, or your whole code might get optimized away.

**Comment by russell-taylor** [comment]
Added in c5429b90a97efce1b758d4e89c93f97bfa280920
