### ISSUE TITLE
Crash when sending a message larger than the appropriate buffer

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#42]
That is, if I let it send a 64011-byte message over Reliable (TCP - 64000 byte buffer), it won't work, and will eventually crash - doesn't print an error message.

**Comment by russell-taylor** [comment]
vrpn_Connection::pack_message() calls vrpn_EndpointIP::pack_message(), which calls vrpn_Endpoint::tryToMarshall(), which calls vrpn_Endpoint::marshall_message(), which checks to make sure we're not overfilling the buffer and returns 0 (nothing sent) if we are.  tryToMarshall() will send any pending messages to make room if it needs to and then returns 0 if it cannot fit the message into the emptied buffer.  vrpn_EndpointIP::pack_message() returns -1 if it can't marshall.  vrpn_Connection::pack_message() then returns -1.  So if I read the code right, all the stuff in the vrpn_Connection class should be working and should not crash. Added code to test_vrpn that exercises these cases, and it seems to be working.

**Comment by russell-taylor** [comment]
It looks like the vrpn_Imager_Server::send_region_using_base_pointer() may not be doing all the checking it should ahead of trying to send, which could cause memory issues.  It should be issuing an error when trying to call pack_message(), so not sure how you're getting there without an error.  Can you send a simple example that crashes (or just the code snippet that deals with the imager) so I can track this down?

**Comment by rpavlik** [comment]
So we're not actually using vrpn_Imager - using a custom class that 
calls pack_message.

Ryan

**Comment by russell-taylor** [comment]
Okay.  The pack_message() code in the vrpn_Connection now has tests showing that it won't try to pack if you ask it for something that is too large.  If you point me at the code that caused the problem, I can try to take a look at it.  Otherwise, we should probably close this.

**Comment by rpavlik** [comment]
OK, so we'll call the tests good.
