### ISSUE TITLE
Reference to vrpn_Connection::set_tcp_outbuf_len is outdated

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#43]
Looks like that method has been moved to an endpoint class and is at least not easily accessible to applications. (Its feature of returning the current buffer length when called with a negative value is also not documented.)

**Comment by rpavlik** [comment]
this is around line 91 of `vrpn_Connection.h`  - Further, it looks like the buffers are statically allocated on both client and server, so not sure how this would work without replacing that static buffer with a vector (which is probably good anyway)

**Comment by russell-taylor** [comment]
I've run into trouble when sending and receiving on the same thread with trying to send arbitrarily-long things through TCP.  The network will fill up its outbound and inbound buffers and then block the write, and then you get deadlock.  This can also make an arbitrarily-long callback handler on the client side, causing rendering burps or worse.  I strongly recommend not trying to change the transport protocol to be infinite but rather to change the objects being sent to be broken up into finite-sizes chunks.

**Comment by rpavlik** [comment]
ugh, that's a drag. What do we have network protocols with segmentation for if not for sending big things? I suppose the next best thing would be to write a fairly generic segmentation handler subsystem, so that anything hitting the ceiling could use it with little extra effort.

**Comment by russell-taylor** [comment]
Removed in 6b1bde2731a0e53e8a033791db79f7a31afa500b and updated the comment to say why we can't change it.
