### ISSUE TITLE
YEI: some sensors report bad temperature

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#45]
per @yboger at GDC, some sensors used in HMDs are reporting -200C even inthe YEI sensor suite, which causes a reset loop because of this line:

https://github.com/vrpn/vrpn/blob/master/vrpn_YEI_3Space.C#L342

**Comment by russell-taylor** [comment]
Took out that check and pushed the changes to the repository.  This will mean that we sometimes miss a shifted report, but will solve the pain for today.  There are other checks in there that should also detect problems, so we're probably okay leaving this out.  Never expected to work below 0 degrees. :-)

**Comment by rpavlik** [comment]
Mind if I re-open this? I already did the workaround on a branch, and I've told the folks at GDC to put their sensor info in this bug, so we can figure out what devices give bad temp data.

**Comment by russell-taylor** [comment]
Be my guest.

**Comment by rpavlik** [comment]
well, since we didn't get any data, I'm just going to say it's YEI's problem that their sensors report bad data. 

Since it's not reliable data, we could remove it from the streaming reports. Ostensibly this would save latency. Not sure if anyone is using it, though.

**Comment by russell-taylor** [comment]
I removed the check, so bad data won't cause problems.  The latency is negligible; this is another byte or two in the middle of a USB packet and a network packet.

**Comment by rpavlik** [comment]
No, I mean from the sensor - YEI mentioned that if you have too many slots in the streaming filled, it increases latency inside the sensor.
