### ISSUE TITLE
Extend WiiMote support to Mac

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#54]
The library that VRPN uses to talk with the WiiMote does not work on the Mac, and the devices cannot be paired with some versions of Mac OSX.

Consider using WJoy as an example of using WiiMote on the mac.

(Note: More recently-manufactured WiiMotes don't work on any OS, they use a variant of the bluetooth protocol that seems to not let them pair.)

**Comment by rpavlik** [comment]
Pretty sure this is invalid now - My WiiUse fork does have mac support, and I think even support for the new ones.
