### ISSUE TITLE
3Dconnexion device completeness

### ISSUE THREAD

**Issue by russell-taylor** [vrpn/vrpn#61]
Found on their website a list of all their product IDs: http://www.3dconnexion.com/index.php?id=200&faq_red=faq/27

See also: http://www.3dconnexion.com/forum/viewtopic.php?p=21095&sid=fccfa9e425306a5306f77322cb5e6f07#p21095

Not sure if those are compatible with the existing driver as the already supported ones are, but perhaps.

Note from Russ Taylor: These devices do not all use the same protocol.  We'll need someone with each device to at least verify that each driver works.

**Comment by bilke** [comment]
I can help by testing the following devices:

- SpaceNavigator
- SpaceMouse Wireless
- SpacePilot

**Comment by mruffat** [comment]
About the SpaceMouse Wireless, it only provides translation values using VPN 7.31. We've already noticed that the packet size of the device reports is 13 bytes, so bigger than expected. That's why the parsing is incomplete and therefore the orientation values are missing.
I hope to have some time to try to fix this in the upcoming months...

**Comment by russell-taylor** [comment]
Glad to have help with this!

**Comment by a3dbox** [comment]
Hi, I have been working on a getting both the SpaceMouse Wireless and SpaceMousePro Wireless working today.  Will do a pull request some time tomorrow assuming it works for my needs.  I have derived a 3DConnectionWireless class for the wireless devices but have not attempted to tidy any of the current code.

**Comment by mruffat** [comment]
This is a good news, thanks!

**Comment by russell-taylor** [comment]
Closing this due to not having access to a set of devices to test on.  As people want drivers for new devices, new issues can be created.
