### ISSUE TITLE
Wiki: some links and formatting lost when transferred from web site

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#69]
I noticed this on the supported devices page, but it's also elsewhere: links went missing, as did formatting. Info on how to do formatting and links is here: https://guides.github.com/features/mastering-markdown/  and you might consider running the web site through an HTML to Markdown converter to automate some of this.

**Comment by russell-taylor** [comment]
The support-devices page is the only one I'm really worried about.  I don't think we lost much on the other pages, and I put back the important things by hand.  I'll look for a converter for the devices page.

**Comment by russell-taylor** [comment]
This has been updated, and re-alphabetized.  I used a markdown converter on the remaining pages that were pulled.
