### ISSUE TITLE
safe sprintf

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#70]
http://randomascii.wordpress.com/2013/04/03/stop-using-strncpy-already/

**Comment by russell-taylor** [comment]
Added vrpn_strcpy() and replaced many of the strncpy() calls in the code with it.  Checked on the other ones that could not use this templated function to ensure that they were doing all that they needed to, and fixed them when they were not.  Updated in commit f5a2aa4e68c1f6190e33e25668cdbf2715230d9e
