### ISSUE TITLE
Build failure when building for Android platform level 21

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#78]
(aka Lollipop) A weird error: 

```
C:\Users\Ryan\Desktop\src\OSVR-Android-Build\src\OSVR-Core\vendor\vrpn\vrpn_Connection.C: In function 'int vrpn_start_server(const char*, char*, char*, const char*)':
C:\Users\Ryan\Desktop\src\OSVR-Android-Build\src\OSVR-Core\vendor\vrpn\vrpn_Connection.C:2527:51: error: 'wait3' was not declared in this scope
             deadkid = wait3(&status, WNOHANG, NULL);
                                                   ^
```

Suggests either they removed a function from the NDK in that platform (unlikely but possible) or they moved it to a different header (more likely).

FWIW, using the CrystaX NDK 10.1.0

**Comment by rpavlik** [comment]
In platform 14 it's in `sys/wait.h`

**Comment by rpavlik** [comment]
Looks like those functions are obsolete and can be replaced with `waitpid`: http://linux.die.net/man/2/wait4  Now, the question is, what "obsolete" systems are being broken by such a change?

**Comment by janoc** [comment]
Fix here: https://github.com/vrpn/vrpn/pull/93
