### ISSUE TITLE
Server crash after/during client disconnect

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#83]
Got a crash in `vrpn_Connection_IP::drop_connection(int whichEndpoint)` with `whichEndpoint = 1`, somehow `endpoint` ended up being null. Backtrace isn't very helpful - parent call is just the connection mainloop.

**Comment by rpavlik** [comment]
Inspecting the `d_endpoints` array, they're all null except entry 0.

**Comment by russell-taylor** [comment]
Is this from multithreaded code?

**Comment by rpavlik** [comment]
This is the OSVR server and some multiple-context client test apps. There are technically multiple threads in the server, but only one actually does VRPN stuff. (The crash was the server when the test client exited - test clients shown here: https://github.com/OSVR/OSVR-Core/compare/test-multiple-contexts )

**Comment by russell-taylor** [comment]
I wonder if mainloop() is being called on the vrpn_Connection object after it was deleted.  Note that the ^C handler in Windows runs IN A SEPARATE THREAD from the main program.  This has bitten me before -- when I delete objects in the ^C handler but the main code is still operating on them.  My solution is to set a "done" or "quit" boolean in the handler that makes the main program quit.

**Comment by russell-taylor** [comment]
...except that client disconnect should not be on another thread.

**Comment by russell-taylor** [comment]
I'm trying to think about how the OSVR server code can crash on this when the standard vrpn_server.exe does not. What server objects is it using, and is one of them removing the reducing count on a connection in a dropped-connection handler?  Having a dead stack above the connection's mainloop() makes me quite suspicious...

**Comment by rpavlik** [comment]
Well, it's not a dead stack (not memory corruption), it's just very short and not very insightful.

**Comment by rpavlik** [comment]
I would say it's the ctrl-c in the client that's causing issues, except this happened when running a test program to completion.

**Comment by rpavlik** [comment]
If I don't see this again soon, I'm going to assume that #87 fixed it.

**Comment by russell-taylor** [comment]
Closing since it has been awhile -- looks like you nailed it with the earlier commit!
