### ISSUE TITLE
Run all automated tests with ctest

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#88]
Right now it looks like it's just running `test_vrpn` and `test_loopback`. If there are others that can be fully automated (`test_logging`? others?) we should get those added to ctest as well, since the autobuilders do the ctest thing.

**Comment by russell-taylor** [comment]
test_imager can be added.  The others either need devices or arguments or don't match CTest semantics (don't exit when done...)

**Comment by russell-taylor** [comment]
Added in 2707db6f6b1e5ee3508aca7455b338448da1f7b9
