### ISSUE TITLE
Makefile build for Travis

### ISSUE THREAD

**Issue by rpavlik** [vrpn/vrpn#90]
If the Makefile build is still interesting to anyone, we should add to our travis-ci configuration to test it, since it's already our pull-request builder. Seems like neatest way is with an `env` list to add another axis, though we could add it as another build step besides the cmake-based one.

**Comment by russell-taylor** [comment]
"Anyone" in this case would refer to those outside the group.  You could post to the mailing list and maybe people would respond.  I know that the FTP download was at one time linked into auto-build systems, but they would pull old versions.

I would imagine that there are people out there using the Makefile and the VS projects who have never converted over to CMake.

**Comment by russell-taylor** [comment]
Somewhat to my surprise, the Makefile still works on a pc_linux64 build.  It may not have the latest drivers in it, but it compiles and runs.  Given that we've had nobody ask for it, lets leave it alone as far as CI goes.  We can fix problems as they are reported for those that are still using Makefile.
